### ISSUE TITLE
这个项目和workflow项目里的WFGraphTask有点像

### ISSUE THREAD

**Issue by Barenboim** [ChunelFeng/CGraph#1]
用户问的比较多的是数据的传递问题，后继结点有没有统一的方法拿到它依赖结点的运行结果。是不是目前用户还需要自己来处理数据传递？

**Comment by ChunelFeng** [comment]
您好，这个刚刚开始做。在优化dag的并行度，数据传递方式还没做。
接下来有空的时候，应该会做数据传递。这个肯定是要做统一的获取和传递方式的

**Comment by Barenboim** [comment]
并行度这块我们的做法是每个节点都包含一个计数器，计数器的目标值就是节点入度。
每个节点执行完成，就count一下它后继节点的计数器，达到目标值了，计数器调起它对应的节点。
而所有的计数器一开始都被放入一个大的并行任务里，graph启动时都一起启动，这时那些入度为0的节点就直接调起了。

**Comment by ChunelFeng** [comment]
我目前也是这样做的，但是我认为是有优化空间的。
暂时能想到的方法有：
比如，一个图仅有 a->b->c 这一条链路。
则这三个节点，是可以同时被放到一个线程/协程中执行的。
b的执行，不需要等待入度变0，而仅需要等待a执行结束（其实表达的是一样的意思，只是不需要分开线程了）。

这样对单点较长链路，是有帮助的

**Comment by Barenboim** [comment]
嗯嗯。你这个优化方法可以减少线程的切换次数。但仅限于a,b,c都是线程任务（计算任务），而且图的调度和线程池调度耦合有点紧。
其实你这个优化对于多入度多节点也是成立的。无非就是最后一个前驱节点执行结束直接就执行下一个。

**Comment by ChunelFeng** [comment]
感谢大佬指教，我们现在在搞新的功能了。
希望到时候大佬能再指导一下
