### ISSUE TITLE
关于UAtomicQueue的问题

### ISSUE THREAD

**Issue by DinLei** [ChunelFeng/CGraph#10]
`    void waitPop(T& value) {
        CGRAPH_LOCK_GUARD lk(mutex_);
        cv_.wait(lk, [this] { return !queue_.empty(); });
        value = std::move(*queue_.front());
        queue_.pop();
    }
`
您好，我是cpp并发刚入门的同学，关于您代码里的"条件变量等待条件"，我在《c++并发编程实战》中看到应该用unique_lock，因为wait条件不满足时需要解锁进入阻塞状态，当wait条件满足时还需要保持锁状态直到函数执行完成。书里讲lock_guard不提供这样的灵活性。请问您这里用法是否有问题，或者是我对书本理解片面了？求指导！

**Comment by ChunelFeng** [comment]
```cpp
template <class _Predicate>
void condition_variable::wait(unique_lock<mutex>& __lk, _Predicate __pred) {
    while (!__pred())
        wait(__lk);
}
```

感谢指正，以上是cv.wait()的源码，需要传入的是unique_lock类型。
刚才尝试，按照原先的方式，传入lock_gaurd类型是会编译报错的。
之前代码之所以没报错，是因为这个类是模板类，而且这个函数没有被执行到。

最近几天对这个CGraph做了不少改动，包括一些多线程方面的内容，请大佬再帮忙review一下。
希望能跟大佬取得联系，以便今后随时交流。

我的微信是： ChunelFeng

**Comment by DinLei** [comment]
您客气啦～我是做算法相关的，后台能力差得不少，正在看源码学习，看到有博客推荐您的这个项目就来学习了，您才是真的大佬

**Comment by ChunelFeng** [comment]
> 您客气啦～我是做算法相关的，后台能力差得不少，正在看源码学习，看到有博客推荐您的这个项目就来学习了，您才是真的大佬

哈哈哈，我也是nlp方面的爱好者。。。有机会多多指教哈
