### ISSUE TITLE
linux系统中使用cmake作为第三方库引用到自己项目

### ISSUE THREAD

**Issue by greent2008** [ChunelFeng/CGraph#102]
需要在主项目CMakeLists.txt中加入
file(GLOB_RECUSE CGRAPH_SRC_LIST "CGraph/src/*.cpp")
add_library(CGraph OBJECT &{CGRAPH_SRC_LIST})
才编译通过
如果只是按照作者在视频讲解中的步骤增加
include(CGraph/cmake/CGraph-env-include.cmake)
add_executabel(my_project $<TARGET_OBJECTS:CGraph> ${PROJECT_SOURCES})
这样cmake会编译不过 会报
$<TARGET_OBJECTS:CGraph>
Objects of target "CGraph" referenced but no such target exists 错误

**Comment by ChunelFeng** [comment]
话说，你这个 add_executabel(my_project {PROJECT_SOURCES}) 

是不是没有加入 $<TARGET_OBJECTS:CGraph> 导致的？

参考视频：https://www.bilibili.com/video/BV1sj411c79y/?spm_id_from=333.999.0.0&vd_source=2c7baed805c6cb33d630d5d4546cf0be

**Comment by greent2008** [comment]
$<TARGET_OBJECTS:CGraph>加了 不知道为什么github这个编辑器没有显示出来

**Comment by greent2008** [comment]
$<TARGET_OBJECTS:CGraph>加了 不知道为什么github这个编辑器没有显示出来
