### ISSUE TITLE
请问是否支持嵌套并行，或者运行过程中根据需要创建任务？

### ISSUE THREAD

**Issue by Frandy** [ChunelFeng/CGraph#103]
比如四个任务A, B, C, D, 依赖关系如下
A --> B，
A --> C,
B--> D，
C --> D，
可以根据这个关系建一个图，启动并行。
在实际应用中，可能B/C的规模可能比较小，有时候也可能比较大。
那么希望在B/C规模比较大的时候，B/C能够创建一些子任务，以便增加并行。
那么这个时候应该怎么创建子任务，创建的子任务放到哪里呢？
从文档里看到有global任务队列，也有本地任务队列，一般把子任务放到本地任务队列里，亲和性更好一些。

是否可以增加这样的demo 呢？

**Comment by ChunelFeng** [comment]
您好，关于你提到的 B中创建子任务，可以将B 设置为一个 group，然后往其中添加node。

例子可以参考：https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T03-Region.cpp
介绍视频可以参考：https://www.bilibili.com/video/BV1Mo4y1h74y/?vd_source=2c7baed805c6cb33d630d5d4546cf0be

应该可以match 到你的想法。
欢迎随时交流

**Comment by Frandy** [comment]
谢谢您的回复。
我看了主页上的文章，和给的demo、视频。
我的疑问在于，是否能在任务执行过程中添加任务或拆分任务？
比如写一个矩阵运算的程序，矩阵的维数根据输入决定。在某种输入情况下，B的大小是1e4, C的大小是100. 
只使用2个线程，B与C并行，C会比B先计算完。然后D就得等着B计算。
我的想法是，在B的实现里，根据矩阵大小，比如按1000的大小，拆分成100个方块，先并行对这100个方块执行计算，然后做后处理完成B的计算。
这里B拆分任务，是需要新建一个pipeline, 往里面放任务，调用pipeline的run/process？ 我好像有看到说pipeline之间是共用thread pool的。

**Comment by ChunelFeng** [comment]
您说的，应该是常用的 AI推理引擎 的工作机制是么?
自动拆分算子（自动优化）的逻辑，色图里是没有的。
如果需要做对应优化的话，还需要在node中，自己实现对应算子优化逻辑。

后期色图会 考虑兼容python版本，方便通过python的通用库，来支持类似功能。
但不会直接开发，主要也是没那个能力，哈哈哈
