### ISSUE TITLE
使用MinGW编译器，编译失败的解决方案。

### ISSUE THREAD

**Issue by Linjinyia** [ChunelFeng/CGraph#105]
使用的MinGW的编译器信息，贴图：
![image](https://user-images.githubusercontent.com/126772685/234580241-822b31ba-1fb9-45c7-ab4f-c8289e53fb48.png)
编译报错信息，贴图：
![image](https://user-images.githubusercontent.com/126772685/234578216-8c39361c-4432-48b3-bc5f-7fc608c0aeaf.png)
解决方案：找到cmake/CGraph-env-include.cmake，具体贴图有：
![image](https://user-images.githubusercontent.com/126772685/234581430-47e18d5b-0f1f-4236-89a1-f239e4fed6e1.png)

**Comment by ChunelFeng** [comment]
感谢提供相关信息
