### ISSUE TITLE
请问能否支持最大并发线程数的计算？

### ISSUE THREAD

**Issue by zpye** [ChunelFeng/CGraph#107]
比如当任务的数量较多时，可能会产生非常复杂的结构，这时是否有方法计算出运行时最多会有多少个线程并发执行，并设置运行时的选择项从而达到更优的调度结果？

**Comment by ChunelFeng** [comment]
这是一个很好的问题，但是想了几天，也找很多朋友聊了这问题。但没有什么好的思路。
我们今后也会随时思考这个问题，如果有什么好的思路，也请随时指教和交流

**Comment by zpye** [comment]
感谢您的回复，我这边也思考了一下，提出这个问题最终的目的是希望获得整体的最高效率，除了可能的并发外，还需要考虑不同节点的执行时间；另外就是线程数的设置和当前机器上的处理器性能也有关系，当线程的数量达到一定规模后，再增加线程整体的性能也不会有明显的提升。

**Comment by ChunelFeng** [comment]
您好，在最新版本中，已经支持针对全node组成的pipeline，进行最大并发度预估。
```
    CSize size = 0;
    status = pipeline->calcMaxPara(size);
```
当 status.isOK() 的情况下， size 值即为所需
