### ISSUE TITLE
引入新的机制，如果是 a->b->c 这种链路的话，就考虑直接单线程执行了

### ISSUE THREAD

**Issue by ChunelFeng** [ChunelFeng/CGraph#110]

**Comment by yeshenyong** [comment]
Wouldn't it be better to give users a choice? I want users to be able to identify their own scenarios and set the operating parameters

**Comment by ChunelFeng** [comment]
Yes, of course, but notice that, some object‘s function used common threadpool, for example GEvent.
We cannot simply stop the malloc of CThreadpool, because this may cause a lot of problem.
