### ISSUE TITLE
cgraph能否在gnode的run方法中获取父节点或子节点对象，并执行父子节点方法获取相关信息？

### ISSUE THREAD

**Issue by starfisher** [ChunelFeng/CGraph#118]
获取父节点或子节点，也可以帮助实现有向图的遍历操作

**Comment by starfisher** [comment]
框架缺少edge边的概念，比如节点与节点连接之间用param包装成固定的edge边可不可以

**Comment by starfisher** [comment]
<img width="1447" alt="截屏2023-05-24 08 16 11" src="https://github.com/ChunelFeng/CGraph/assets/13116353/9c615287-5bd4-4f1d-a46d-f30689d0f933">

**Comment by starfisher** [comment]
是的，有实际开发，上面是我截的一个简单的图，每个算子计算的时候会从father节点获取父节点输出结果，作为本节点的算法输入。

个人如果使用色图的话，确实可能会考虑修改gelement.h，并封装edge的打算。

**Comment by starfisher** [comment]
当然还有其他例子，cicd构建部署工具以及node-RED数据转发这种类型的应用应该也需要。
![image](https://github.com/ChunelFeng/CGraph/assets/13116353/abc323e3-7a0d-4dd6-a8d5-8da9106cc234)

![image](https://github.com/ChunelFeng/CGraph/assets/13116353/49cf7ca3-074a-4100-98d5-bc52682d067a)

**Comment by ChunelFeng** [comment]
您好，最新版本的 GElement.h 文件中，已经提供了 buildRelation() 方法，
方便获取当前节点的 前驱和后继信息，希望对您有所帮助。

再次感谢您的关注

**Comment by starfisher** [comment]
好的，谢谢
