### ISSUE TITLE
已有项目集成CGraph如何保持原有返回状态码？

### ISSUE THREAD

**Issue by BoysFight** [ChunelFeng/CGraph#119]
**背景：** 原有的代码api是返回状态码，状态码定义的种类和数量有点多，而且外部接口关联代码较多，和Cstatus里的定义值不一致（异常错误<0）；

**期望：** 保证api返回状态码定义不变情况下，以改动最小方式把咱们CGraph集成进来么？

我当前想到两个思路：

1. 把已有状态码和Cstatus状态码统一到一个结构体；
    可能存在的问题：需要修改CStatus相关定义，后续Cgraph更新冲突会很多，且修改后状态码值与原来不同；
3. 用异常的方式，保持pipeline里接口还是Cstatus接口不变，原有的代码异常情况抛出异常，在pipeline接口外部捕获，并转换成原来对应定义的状态码对外输出；
    可能存在的问题：不确定接口内部是否保证异常安全，会不会有内存泄露或状态异常？

针对这种场景，官方推荐的实现是怎么样的啊？

**Comment by ChunelFeng** [comment]
1，色图中，所有判断 返回值是否正常的信息，都在 CGRAPH_FUNCTION_CHECK_STATUS 的宏函数中了。如果修改的话，理论上仅需修改一处即可。但是，我也不能保证，因为还有很多判断是否为 null的宏函数
2，如果不想修改色图的情况下，想兼容现有逻辑，可以考虑，添加一层 CStatus中 info_ 信息，和你们原有返回值信息的映射关系。算子中，抛出对应的string 的时候，返回映射的 错误码。
3，色图的函数返回值中，包含 code 和 info 信息，理论上，可以转成任何类型的信息。中间加一层 adaptor即可
