### ISSUE TITLE
关于条件嵌套执行的问题

### ISSUE THREAD

**Issue by RunCodeFly** [ChunelFeng/CGraph#120]
您好，我在版本2.1.0中写了一个有条件嵌套执行的测试程序案例，但发现有些节点没有执行，请帮忙看下是什么原因，下面是我的代码：

void Test3()
{

	/*
							      Node0
							         /  \
							Node1  Node2
							          \  /
							       Node3
							          |
							      条件1
							      /    \
                                                       Node4   Node5
						           |
						       条件2
						         /  \
				                Node6  Node7
	*/

	GPipelinePtr pipeline = GPipelineFactory::create();

	GElementPtr node0, node1, node2, node3,node4,node5,node6,node7 = nullptr;

	node4 = pipeline->createGNode<MyNode1>(GNodeInfo({}, "node4", 1));
	node5 = pipeline->createGNode<MyNode1>(GNodeInfo({}, "node5", 1));
	node6 = pipeline->createGNode<MyNode1>(GNodeInfo({}, "node6", 1));
	node7 = pipeline->createGNode<MyNode1>(GNodeInfo({}, "node7", 1));

	//创建条件2
	GElementPtr condition2 = pipeline->createGGroup<MyCondition>({ node6,node7 }, {node4});
	 
	//创建条件1
	GElementPtr condition1 = pipeline->createGGroup<MyCondition>({ node4,node5,condition2 });

	CStatus status = pipeline->registerGElement<MyNode1>(&node0, {}, "node0", 1);
	status += pipeline->registerGElement<MyNode1>(&node1, { node0 }, "node1", 1);
	status += pipeline->registerGElement<MyNode1>(&node2, { node0 }, "node2", 1);
	status += pipeline->registerGElement<MyNode1>(&node3, { node1,node2 }, "node3", 1);
	status += pipeline->registerGElement<GRegion>(&condition1, { node3 }, "condition1", 1);
	

	if (!status.isOK()) {
		return;   
	}

	status = pipeline->init();
	status = pipeline->run();
	status = pipeline->destroy();

	GPipelineFactory::remove(pipeline);
}

**Comment by ChunelFeng** [comment]
您好，对应的代码思路，和工程不符和。group 中信息，包含的内容，仅包含本group内一层。
修改后的逻辑，如下所示：

```cpp

void tutorial_simple() {
    /*
						      Node0
						         /  \
						Node1  Node2
						          \  /
						       Node3
						          |
						      条件1
						      /    \
                                                   Node4   Node5
					           |
					       条件2
					         /  \
			                Node6  Node7
*/


    GPipelinePtr pipeline = GPipelineFactory::create();


    GElementPtr node0, node1, node2, node3,node4,node5,node6,node7 = nullptr;

    node4 = pipeline->createGNode<MyNode1>(GNodeInfo({}, "node4", 1));
    node5 = pipeline->createGNode<MyNode1>(GNodeInfo({}, "node5", 1));
    node6 = pipeline->createGNode<MyNode1>(GNodeInfo({}, "node6", 1));
    node7 = pipeline->createGNode<MyNode1>(GNodeInfo({}, "node7", 1));

    // 在 cluster1 中，先执行 node4的逻辑，在执行 condition{node6, node7} 逻辑
    GElementPtr cluster1 = pipeline->createGGroup<GCluster>(
            {
                    node4,
                    pipeline->createGGroup<MyCondition>({node6, node7})
            }
            );
    
    GElementPtr condition1 = pipeline->createGGroup<MyCondition>({ cluster1, node5});

    CStatus status = pipeline->registerGElement<MyNode1>(&node0, {}, "node0", 1);
    status += pipeline->registerGElement<MyNode1>(&node1, { node0 }, "node1", 1);
    status += pipeline->registerGElement<MyNode1>(&node2, { node0 }, "node2", 1);
    status += pipeline->registerGElement<MyNode1>(&node3, { node1,node2 }, "node3", 1);
    status += pipeline->registerGElement<GRegion>(&condition1, { node3 }, "condition1", 1);

    pipeline->process();

    GPipelineFactory::remove(pipeline);
}

```


btw，当前最新版本中，有 pipeline->dump() 的逻辑，可以帮助快速查看 dag结构图，
也加入了一些调度优化的思路，推荐升级。
