### ISSUE TITLE
未禁止外部拷贝和赋值

### ISSUE THREAD

**Issue by shiyiyuedeyu** [ChunelFeng/CGraph#124]
https://github.com/ChunelFeng/CGraph/blob/c02116c26994cb0698e5ea7cf870b8c1745afe72/src/UtilsCtrl/Singleton/USingleton.h#L20

**Comment by shiyiyuedeyu** [comment]
USingleton(const USingleton &signal);
    const USingleton &operator=(const USingleton &signal);

**Comment by ChunelFeng** [comment]
收到，感谢您的意见和对项目的关注。单例类，的确不应该提供 copy 的方式。
不知您是否有兴趣，帮忙修改掉这个问题。
推荐参考 CGRAPH_NO_ALLOWED_COPY() 这个宏的用法

btw，希望可以跟您取得联系，以便随时请教和交流。
项目 readme中，有我的个人联系方式。
