### ISSUE TITLE
windows 10下使用CLion 2023.1.3 三方引入CGraph编译报错处理

### ISSUE THREAD

**Issue by winetx-winetx** [ChunelFeng/CGraph#127]
1. 编译报错
![image](https://github.com/ChunelFeng/CGraph/assets/537582/4d50a76b-993b-4c6e-a8be-d038cb44f0cd)

2. CGraph-env-include.cmake修改前
![image](https://github.com/ChunelFeng/CGraph/assets/537582/ca5c3e9f-ac0f-430d-ae98-0f884ef68c94)

3. CGraph-env-include.cmake修改后
![image](https://github.com/ChunelFeng/CGraph/assets/537582/7aa8218a-95d0-47e4-b815-c21b0e446549)

4. 编译成功
![image](https://github.com/ChunelFeng/CGraph/assets/537582/2a5650c4-4d67-42d7-97a8-28740ebc79f3)

**Comment by ChunelFeng** [comment]
感谢您的关注和反馈，新版本色图中，已经在对应场景的位置，给出明确提示

<img width="1430" alt="image" src="https://github.com/ChunelFeng/CGraph/assets/37905059/df06f023-aba4-45b3-8479-4f26227ddd7a">

欢迎随时提出您的意见和建议，也欢迎给项目提供有意思的pr
