### ISSUE TITLE
由于引入了QtWidget动态库，GParam中属性值异常

### ISSUE THREAD

**Issue by zmoth** [ChunelFeng/CGraph#135]
相关问题 #133 #134 

OS: win10
编译器: MSVC 2022
Qt版本: 6.5.0

复现代码地址 https://github.com/QianMoth/mvc-demo/tree/dev

**Comment by zmoth** [comment]
在GParam create中，通过CGRAPH_SAFE_MALLOC_COBJECT开辟了一段内存 其地址是0x00000181259b3ea0,关注以下key内容和地址
![image](https://github.com/ChunelFeng/CGraph/assets/55644167/d1e21f80-03de-4efa-94e8-08950714b8c6)

然后在`TGParam* getGParam(const std::string& key)`中，对`param_manager_`搜索param1 返回的地址是00000181259B3EA0

之后进入`addBacktrace`,发现debug信息均正常，指针也对，但是log中打印的不一样
![image](https://github.com/ChunelFeng/CGraph/assets/55644167/a20ecd7f-ca4e-45a6-bc7a-d12c05358c86)

**Comment by zmoth** [comment]
**当注释掉Qt的引入**

![image](https://github.com/ChunelFeng/CGraph/assets/55644167/eb73653d-5a64-4352-853c-e4d4906ecf5d)

![image](https://github.com/ChunelFeng/CGraph/assets/55644167/d1c519c3-729a-4fb9-a81e-6305833f68c4)

**Comment by zmoth** [comment]
**当保留Qt库引入，但是改变GParam属性的顺序**
```cpp
private:
    CBool backtrace_enable_ = false;                             // 是否使能backtrace功能
    std::string key_;                                            // 对应的key信息
    USerialUniqueArray<std::string> backtrace_;                  // 记录参数的调用栈信息，仅记录get 此参数的地方。不包括 create和remove的地方。
    USpinLock backtrace_lock_;                                   // 针对backtrace的自旋锁
```

![image](https://github.com/ChunelFeng/CGraph/assets/55644167/fe53c572-4b81-4998-aa36-46517569ccfc)

![image](https://github.com/ChunelFeng/CGraph/assets/55644167/3279c840-9575-404b-b2f9-e09c5a375223)

**Comment by ChunelFeng** [comment]
我还想到有一个事情，GParam 类，自己是没有构造函数的。
请抽空再帮忙确认一下，如果不改动原来的内容，仅添加构造函数，在构造函数中，对 bt_enable 字段赋值，是否还会出现异常情况。

感谢您的pr，欢迎随时交流

**Comment by zmoth** [comment]
> 我还想到有一个事情，GParam 类，自己是没有构造函数的。 请抽空再帮忙确认一下，如果不改动原来的内容，仅添加构造函数，在构造函数中，对 bt_enable 字段赋值，是否还会出现异常情况。
> 
> 感谢您的pr，欢迎随时交流

当自己创建构造函数时，直接就异常了 `Critical error detected c0000374`

不引入QT时正常。

![image](https://github.com/ChunelFeng/CGraph/assets/55644167/fe62c3a0-6927-4303-bfa7-7c2276c80c61)

**Comment by zmoth** [comment]
另外我尝试了降低Qt版本为6.4.3

使用mingw_64正常
使用msvc2019_64还是异常

**Comment by ChunelFeng** [comment]
> 

那看起来，更像是 qt lib的问题了
