### ISSUE TITLE
init()没有按依赖执行

### ISSUE THREAD

**Issue by whenever5225** [ChunelFeng/CGraph#14]
不同算子的init()是随机执行的吗？能不能按照设定的依赖关系执行？

**Comment by ChunelFeng** [comment]
您好，您提出的这个问题，我们正在解决。但目前遇到了一些原先架构设计下的技术瓶颈。

目前，您可以通过在init函数中createParam，并且在run函数中 设置param值的方式，来解决此问题。

我们也会尽快给出相应方案。

感谢您的意见和建议，敬请关注我们接下来的版本。

**Comment by ChunelFeng** [comment]
您好，针对您提出的问题，
我们优化了 注册registerGElement和createGNode/createGGroup的逻辑，
见下方逻辑：如果您通过以上方式注册，则 init的顺序会是 b->init, a->init，而执行顺序是 a->run, b-run

```cpp
pipeline->registerGElement<MyNode1, 1>(&a, {}, "nodeA");
pipeline->registerGElement<MyNode2, -10>(&b, {a}, "nodeB");
```

其中，具体执行逻辑，还是根据 依赖关系生成的dag来执行。
初始化的逻辑，根据 注册时候设定的 level值（如 1， -10）来先后执行，level 值越低（可以为负数），越先执行init逻辑。
不设定，默认为 level=0， level值相同的 node，init执行顺序随机。

注：destroy执行先后逻辑，与init相同。

**Comment by whenever5225** [comment]
谢谢🙏，太强了！
