### ISSUE TITLE
你好，请教下我的场景是否适用这个框架

### ISSUE THREAD

**Issue by zjd1988** [ChunelFeng/CGraph#141]
也是node组成是pipeline，但是每个节点之间互相有依赖，并且所有node循环执行不退出

**Comment by ChunelFeng** [comment]
您好，感谢您的关注。

色图中，是可以实现 单节点/组/组内插组 等各种形式的循环执行，不退出（等待特定的条件，退出循环）的。
应该可以满足您的需求

类似的demo，请参考：
https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T14-Hold.cpp

如果觉得对您有帮助，请帮忙star，感谢。
如果有其他任何问题，欢迎添加我的微信（ChunelFeng，或者扫描项目中的二维码），随时交流指教

**Comment by zjd1988** [comment]
@ChunelFeng 好的，我先学习下

**Comment by ChunelFeng** [comment]
如果有意见或者建议，请随时指教和交流
