### ISSUE TITLE
CGraph 是否能用在網路封包處理呢?

### ISSUE THREAD

**Issue by davidleitw** [ChunelFeng/CGraph#15]
您好, 最近突發奇想, 并行计算框架常常用來建構一些AI計算的任務. 那是否能把這類框架用於 server 來快速處理封包呢? 

我在想沒有人這樣做是不是因為調度的過程可能比處理封包更耗時間一類的，希望大佬能幫忙解惑一下XD

**Comment by ChunelFeng** [comment]
您好，很高兴能够交流。关于你说的问题，我说一下我的个人看法，仅供参考。

1，首先，当然可以，而且我相信也有很多人/团队在做这样的事情。比如，dag最前面的node接受请求，最后的node返回结果。

2，如您所说，这种留图框架，不太用于server开发，个人理解更多是因为server设计的时候，比较重视高并发开发。如果单纯用一个dag流图，只能保证单独流程，不能用来处理并发问题。

3，我们自己用的后台引擎服务，为了应对高并发，采用了微服务架构。多个服务构建了一个大的dag，每个微服务内部，也是一个小的dag，并且对外提供统一的proxy接入。

dag构图开发，是一种思路，个人认为没有适合或者不适合的领域。主要是看，特定领域需要解决什么样的问题，是否适合图化（除了算法研究之外，暂时没遇到不能图化的逻辑，哈哈哈哈）和 如何图化

**Comment by davidleitw** [comment]
您好, 之前腦袋一直轉不過來覺得 dag 的概念是綁定特定 framework 的，如果只是要把設計圖化的確跟您說的一樣，幾乎所有問題都能轉為圖, 十分感謝您的回答，希望之後有機會可以多交流一些關於後台開發的知識!
