### ISSUE TITLE
搞一个test的框架

### ISSUE THREAD

**Issue by ChunelFeng** [ChunelFeng/CGraph#150]

**Comment by ChunelFeng** [comment]
1. 多输入测试
2. 一键拉起所有的测例

**Comment by ChunelFeng** [comment]
可以一键执行多个 pipeline信息

**Comment by naonao-coke** [comment]
> 可以一键执行多个 pipeline信息，可以同时执行（如message功能测试），也可以串行执行
benchmarck 三方库 行的不？

**Comment by ChunelFeng** [comment]
> > 可以一键执行多个 pipeline信息，可以同时执行（如message功能测试），也可以串行执行
> > benchmarck 三方库 行的不？

如果有你有兴趣的话，可以自己在自己的仓库里，fork 一份逻辑，然后引入三方库，
去进行一些性能分析，gtest，和 benchmark的工作哈。

我们非常需要这样的内容，但是不想在主项目中，引入三方逻辑
