### ISSUE TITLE
考虑动态注册节点

### ISSUE THREAD

**Issue by hellolinfrom2025** [ChunelFeng/CGraph#151]
您好，目前在学习整合色图，看了B站所有视频，感觉很兴奋。
不过也发现优化点：
1、在编译阶段注册节点有些限制，如果能通过反射动态创建节点就好了。
2、GPipeline是否加个当前运行状态函数，我现在通过std::future<CStatus>的值wait 1ms，超时了就证明在运行，感觉有些怪。
3、异步运行咋没运行多次的参数

**Comment by ChunelFeng** [comment]
您好，关于你提到的这几个问题，我说一下我的观点：

1、色图中提供的demo中，均为编译阶段注册。当然，只是最简单的使用说明。
如果需要做动态映射的话，个人建议可以通过自定义json格式等方式，自行开发。项目自身为mit协议，欢迎和支持二创。而且感觉难度不算大。
但项目自身，目前没有引入任何三方库，所以并不是很好解析标准格式的内容。故 暂时没有实现反射功能。
如果有好的思路，也请随时交流和pr。

2、哈哈，这个判定方式，是有点奇怪。
初步想一下，是否可以直接通过一个变量，在外部直接记录pipeline的执行状态？
或者直接在pipeline那一层，添加一个变量即可。

3、异步运行的 asyncProcess() 方法，支持传入执行次数的信息
```cpp
    /**
     * 异步执行pipeline的全部流程
     * @param runTimes
     * @return
     */
    std::future<CStatus> asyncProcess(CSize runTimes = CGRAPH_DEFAULT_LOOP_TIMES);
```

最后，给b站的视频，求个一键三连，感谢您的关注。

**Comment by hellolinfrom2025** [comment]
感谢及时回复，B站视频已投币点赞满上。
1、已经有json做动态创建节点以及它们之间的依赖。但需要提前写好各种类型的GNode。我想法是创建任务流的代码和继承GNode的具体类解耦。一旦写好了动态构建模块，其他插件只要继承GNode，接着根据规则动态注册节点和依赖，目前还没好思路。
3、asyncProcess可以的，之前我先调用init，导致抛异常了。
突然想起，因为我用windows+vs2022开发，下载的最新2.4.2源码，可以编译静态库。但新建一个项目导入头文件和lib，还是会因为换行符问题，导致编译错误，我手动把文件一个一个换成CRLF才编译通过😂

**Comment by ChunelFeng** [comment]
不是很了解您第一条所说的内容的具体含义。方便的话，请附上简单的例子。

哈哈，第三条是因为linux和windows字符不兼容，
可以百度一下，git clone的时候，有一个设置，可以有效的避开这个问题。

**Comment by hellolinfrom2025** [comment]
第一条例子还没写，只是一个需求和想法。大概是注册节点（registerGElement）是一个模块（dll或so），称为流程管理模块，继承节点（CGraph::GNode）又是新模块，称为功能模块。功能模块负责实现具体功能，并注册到管理模块上。管理模块通过字符串动态创建任务流。用到了多态+对象工厂模式。我新写一个不是模板函数的registerGElement，传递运行时子类指针进去，可以么，纯大？

我从tag的下载正式版zip版本，这可以git么。

然后，发现个bug：asyncProcess(CSize runTimes = CGRAPH_DEFAULT_LOOP_TIMES);
当我参数是最大值时（期望死循环），接着它后台正常运行，一段时间后调用cancle()，节点确实不执行，但是while还在减1，没有break。  while (runTimes-- > 0)
``` C++
CStatus GPipeline::process(CSize runTimes) {
    CGRAPH_FUNCTION_BEGIN
    status = init();
    CGRAPH_FUNCTION_CHECK_STATUS

    while (runTimes-- > 0) {
        status = run();
        CGRAPH_FUNCTION_CHECK_STATUS
    }

    status = destroy();
    CGRAPH_FUNCTION_END
}
```

**Comment by ChunelFeng** [comment]
关于第一个问题，我感觉上应该是可以实现的，具体实现方案请自行思考。
配合上您之前提到的 文本配置的话，思路尤佳。

关于您提到的 asyncProcess的时候，无法cannel，我看了一下，的确有这种问题。
如果需要 cancel 当前pipeline的话，请考虑通过 init->asyncRun() * n +destroy的方式实现。

我们接下来也会尽可能快的修复这个问题。再次感谢您的宝贵意见

**Comment by ChunelFeng** [comment]
关于第一个问题，我感觉上应该是可以实现的，具体实现方案请自行思考。
配合上您之前提到的 文本配置的话，思路尤佳。

关于您提到的 asyncProcess的时候，无法cannel的问题，请参考以下写法：

![image](https://github.com/ChunelFeng/CGraph/assets/37905059/6b4b24ff-d267-4a31-8ccd-80cb504bed39)

**Comment by hellolinfrom2025** [comment]
纯大，你试试runTimes为std::numeric_limits<CSize>::max()，1000还是小了。

**Comment by ChunelFeng** [comment]
get 到您提到的这个点了。
这是色图cancel机制 设定的问题，我们接下来考虑一下如何避免类似问题。

再次 感谢您提供的信息

**Comment by ChunelFeng** [comment]
在我们修复之前，如果需要用到类似机制，建议通过 init + asyncRun()*n + destoy 的方式处理

**Comment by hellolinfrom2025** [comment]
好的，考虑加个获取异步运行状态的函数么，可以方便安全的start（asyncProcess）和stop（cancle）。
我目前是这么做的
``` C++
bool TaskFlow::isRun()
{
    if (!f_ret_.valid()){
        return false;
    }
    auto status = f_ret_.wait_for(std::chrono::microseconds(500));
    return std::future_status::timeout== status;
}
```

**Comment by ChunelFeng** [comment]
> 好的，考虑加个获取异步运行状态的函数么，可以方便安全的start（asyncProcess）和stop（cancle）。 我目前是这么做的
> 
> ```c++
> bool TaskFlow::isRun()
> {
>     if (!f_ret_.valid()){
>         return false;
>     }
>     auto status = f_ret_.wait_for(std::chrono::microseconds(500));
>     return std::future_status::timeout== status;
> }
> ```

最新版本中，已经修复了 cancel 的时候，阻塞时间过长的问题。
并且添加了 pipeline->getCurState() 方法，用于获取pipeline当前的执行状态。

再次感谢你的意见。

**Comment by hellolinfrom2025** [comment]
感谢采纳更新，我clone后，继续测试，有问题再咨询。

纯大，对于习惯从Release下载正式版源码zip的部分人，且又是Windows平台，此时源码文件换行符还是LF。新工程编译时会报错，您看有何优化方式么，比如从cmake上判断平台，切换换行符啥的。

**Comment by ChunelFeng** [comment]
之前有童鞋遇到过类似的问题，如果通过 git下载的话，需要添加一个配置信息，参考：https://github.com/ChunelFeng/CGraph/issues/8

如果是直接 download zip的话，可以控制的流程较少。
这个我记得，应该是可以通过 visual  studio 上的配置设置的，请自行搜索一下。

如果有什么好的实现思路，或者是 cmakelist上有什么配置方式的话，欢迎随时告诉我们，或者pr过来

**Comment by ChunelFeng** [comment]
如果还有其他问题，请随时交流。
再次感谢您的关注和建议
