### ISSUE TITLE
关于异步执行管道的状态问题

### ISSUE THREAD

**Issue by hellolinfrom2025** [ChunelFeng/CGraph#153]
Hello，纯大。
最近修改的异步运行状态，使用后发现几个bug：
1、asyncProcess()正常运行完，状态还是Normal，导致之后调用getCurState()不准确
2、处于运行状态并调用cancle()后，状态维持Cancle，再次调用asyncProcess()无法进入while里执行run()
管线执行了destroy()，状态要还原到Create?

以下是我的使用方式：
![image](https://github.com/ChunelFeng/CGraph/assets/38918324/47951538-e114-4b44-941d-28a2e8579add)

**Comment by ChunelFeng** [comment]
最新版本中，已经修改这一块的逻辑。最新逻辑的内容是：
无论是 cancel 结束，还是异步执行完成后结束，所有的状态，均恢复为 CREATE （类似init刚执行完）的状态。

感谢您的宝贵意见

**Comment by ChunelFeng** [comment]
![image](https://github.com/ChunelFeng/CGraph/assets/37905059/4bd30673-38be-4007-9624-61e4222b5b6e)

请关注相关内容
