### ISSUE TITLE
cpu使用率过高？

### ISSUE THREAD

**Issue by hellolinfrom2025** [ChunelFeng/CGraph#159]
Hello，纯大。
运行T01demo，cpu使用率太高了，直接占满我剩余的cpu，到100%。
测试环境：Windows，vs2022，debug
代码：T01-Simple

![image](https://github.com/ChunelFeng/CGraph/assets/38918324/1d2ee6ff-e4f5-410a-958c-3e318dbe9798)

**Comment by hellolinfrom2025** [comment]
了解了，我修改试试。

**Comment by ChunelFeng** [comment]
> 了解了，我修改试试。

btw，针对你上次提到的 win和linux 换行符不一样的问题，
我们在最近的版本中，已经提供了解决方案。

推荐尝试

**Comment by ChunelFeng** [comment]
符合预期。本修改是在最新版本的，引入的win和linux兼容的机制，
并没有修改之前的release版本的内容。

**Comment by ChunelFeng** [comment]
请更新最新版本，其中，T01-Sample.cpp 中，有一处改动。
打开以下配置选项之后，可以有效的降低 cpu负载。


```cpp
    UThreadPoolConfig config;
    config.default_thread_size_ = 2;
    config.extreme_speed_enable_ = false;    // 新加入的配置信息
    pipeline->setUniqueThreadPoolConfig(config);
```

**Comment by hellolinfrom2025** [comment]
好嘞

**Comment by hellolinfrom2025** [comment]
> 

Hello，纯大。
新版本改动对哪里生效呢？通过git可以转换换行符，直接下载zip再cmake还是LF的。这次从main仓库直接下载。

然后有个疑问：
cmkae生成的sln方案，缺少了INSTALL工程，它能自动打包include和lib到一个文件夹。
![image](https://github.com/ChunelFeng/CGraph/assets/38918324/e44629ba-3ca3-4780-a7db-a765539eb79d)

**Comment by ChunelFeng** [comment]
修改换行符的思路，是通过 .gitattr文件中的设定，直接clone zip 应该是不设计这个特性的吧。

关于 make install的问题，由于色图编排文件，不是通过 include 和 src两个文件夹放置的，
而是所有代码都放到 src文件夹中。

如果有好的跨平台的实现思路，欢迎pr
