### ISSUE TITLE
关于GElementManager中的逻辑

### ISSUE THREAD

**Issue by Burgundy-Red** [ChunelFeng/CGraph#16]
菜鸡提问，没看懂GElementManager类中 preRunCheck 和 analyse函数的逻辑，有无大佬帮忙解惑！感谢！

**Comment by ChunelFeng** [comment]
您好，关于您提到的这个问题，推荐您先看一下 readme 下面的介绍文档（第一篇和第二篇）。

如果有什么疑惑，请随时沟通

![image](https://user-images.githubusercontent.com/37905059/188828582-e048b320-131f-4731-91c3-d3fadb9d17b7.png)

**Comment by ChunelFeng** [comment]
感谢您的关注，图算法方面我也是小白，想要了解一些相关知识的话，推荐：https://space.bilibili.com/1369507485/favlist?fid=1302158485&ftype=create 这位大佬的在b站上的这个专题

如果对CGraph项目感兴趣，有什么疑问或者建议的话，欢迎添加我的微信，方便随时交流。
也随时欢迎pr和帮忙优化其中内容

**Comment by Burgundy-Red** [comment]
前几天一直被各种事耽误，现在俺终于看懂了，好像并没有用到啥图论的知识，都是您写的介绍文档的这个循环逻辑。
膜拜大佬。
