### ISSUE TITLE
大佬的线程池写的很赞，有一个问题是把线程池拿到Dll执行，VS2017下出问题了

### ISSUE THREAD

**Issue by shixingya** [ChunelFeng/CGraph#17]
事情是这样的
我把大佬的线程池拿出来工程化了，整成EXE执行程序，运行丝滑无事故。
整成DLL，单例获取线程池直接没LOG输出了。
UThreadPoolPtr tp = UThreadPoolSingleton::get();

目前的解决方式是USingleton.h中，将USingletonType type = USingletonType::HUNGRY 改成
USingletonType type = USingletonType::LAZY，或者将static放到get方法内部执行。

**Comment by shixingya** [comment]
同样封成Dll， 在VS2019，甚至Ubuntu上，执行正常。

**Comment by ChunelFeng** [comment]
感谢大佬帮忙指正，并提出修改意见。

有兴趣的朋友，欢迎加入 [qtcn社区](http://www.qtcn.org/bbs/index-htm-m-bbs.html)，

和大佬本佬 和各路高手一起切磋交流，共同进步

**Comment by shixingya** [comment]
> 感谢大佬帮忙指正，并提出修改意见。
> 
> 有兴趣的朋友，欢迎加入 [qtcn社区](http://www.qtcn.org/bbs/index-htm-m-bbs.html)，
> 
> 和大佬本佬 和各路高手一起切磋交流，共同进步

多谢引流，对有兴趣一起交流QT技术的同学，可以加我微信EagleAndy，备注qt即可
