### ISSUE TITLE
linux环境下，设置线程优先级出现warning

### ISSUE THREAD

**Issue by Burgundy-Red** [ChunelFeng/CGraph#174]
![Screenshot from 2023-08-08 17-04-34](https://github.com/ChunelFeng/CGraph/assets/42458671/4592b165-7811-4c3b-baa4-186a6cfe4b58)
根据https://man7.org/linux/man-pages/man2/sched_get_priority_min.2.html
![Screenshot from 2023-08-08 17-05-38](https://github.com/ChunelFeng/CGraph/assets/42458671/1d4d1d5e-980f-4372-bd07-4add20a05f69)
默认设置为0后，warning消失

**Comment by ChunelFeng** [comment]
感谢您的反馈，最新版本中，已经修复了这个问题。
thread的默认值，修改为了0，策略是 other。
如果在linux上，欢迎做出对应的修改，从而提升效率。

**Comment by Burgundy-Red** [comment]
> btw，想了解一下，您们的实际使用场景，和想使用色图做具体一些什么操作。 兴许我们可以给出一些相应的意见和建议。

大佬您好，俺目前还是一个小菜鸡，还是在学习您的这个项目暂时没有实际使用。后续有机会使用一定和您联系：-）
