### ISSUE TITLE
使用场景方面的交流

### ISSUE THREAD

**Issue by neland** [ChunelFeng/CGraph#175]
CGraph看下来在很多方面都比taskflow更贴近实际场景，更接地气，特别是在参数传递方面
我一直想改造我司的业务系统，我们是一个分布式系统，系统间基于消息通信，有MQ、有Rpc
一个业务功能，需要和多个子系统交互，都是基于异步回调
开发人员需要基于事件回调处理每一个消息，然后再在处理逻辑中串联后续逻辑
```cpp
void CreateA(){
    SendMessage("CreateA");
}
void OnCreateARsp()
{
    if result == ok
          CreateB();
}
void CreateB(){
    SendMessage("CreateB");
}
void OnCreateBRsp()
{
    // 继续后面的流程
}
void MessageCb(msg)
{
     if msg == ev_createa_rsp
           OnCreateARsp()
     if msg == ev_createb_rsp
           OnCreateARsp()
}
```
这样的系统有几个问题
1、业务开发需要在大量的异步逻辑中串联业务逻辑
2、新的开发人员无法直接看出业务流程

理论上，可以将子任务的请求和响应抽象为Node，将功能抽象为Pipeline。

看了很多任务调度相关的库，其实都很少提及与基于已有消息系统如何关联，或者说没有实践参考
不知道在这个场景下有什么改造建议或编程范式

**Comment by ChunelFeng** [comment]
您好，感谢您的关注。我没有很多端开发和异步开发的经验，关于上面提到的几个问题，我说一下我个人的看法：

1，如果不考虑大量数据库调用等io逻辑，个人推荐是，外部一个接受请求的组件（如 workflow），然后通过key 分发到不同的pipeline中，最终将pipeline计算的结果，返回出去即可。这样的话，可以确保业务流程中0回调逻辑。

2，关于新人如何看业务流程，色图提供了 dump() 功能，可以将 当前的pipeline信息，通过 graphviz的形式展示出来，方便人了解和入门。其中，每个node的逻辑，不建议写的太长，以便于阅读

之前实现了一个简单版本的 nio版本的色图，https://github.com/CDev-io/CGraph-NIO   
思路是通过workflow 来接收和返回外部请求，通过CGraph 来实现具体的处理逻辑，
有兴趣的话，可以参考一下，也欢迎指正。

btw，为了针对后端开发的情况，色图提供了单个线程池调度多个pipeline的方式，一定程度上可以提高后台处理效率。
如果业务流程是 纯串行逻辑，也推荐 使用 色图的串行执行功能。

**Comment by neland** [comment]
感谢，workflow也研究过，主要是我们系统的消息通信无法大范围改造，也有一些场景不适合Rpc，所以只是想找一个任务流的库，后续只能再多看看

顺带提个小建议
我看有小伙伴也提到过，关于CGraph的一些命名有些擦边--!，给我的感觉并不是擦边，更多的可能是会让人觉得不严谨
既然付出那么多，现在star马上过千，如果有志破万，可能真需要考虑下

**Comment by ChunelFeng** [comment]
HI，如果有命名不严谨的地方，请随时指出，或者pr相关 内容。表示感谢。
刚才上传了关于node 异步执行的方式，可能对异步coding有一点帮助。
by the way，色图中也可以考虑用 event 来描述用来响应事件的 串行逻辑信息

如果对色图项目感兴趣，非常欢迎加入，一起共建，
如果有实际项目目标，或者想法，也欢迎通过微信（或者语音会议）的方式，跟联系我们，
我们也想了解一些实际的应用场景，以及我们在落地过程中的差距和不足。

我们对star数，并没有太明确的目标（年初的时候，我们几个还在聊，今年能不能过1000，哈哈）
但的确想做一个简单好用的调度引擎，并且能为行业做一点力所能及的贡献
