### ISSUE TITLE
节点之间的依赖关系

### ISSUE THREAD

**Issue by kkonghao** [ChunelFeng/CGraph#177]
您好，可以在创建节点的时候指定节点的依赖关系(指定父节点即可,说明依赖父节点的计算结果)和设定节点名称，从而简化创建流水线和节点注册并指定依赖关系的复杂度吗，假如我现在有1000个节点，一个一个的 注册节点和设定依赖关系困难是难以想象的，出错的概率也很大。

**Comment by ChunelFeng** [comment]
<img width="758" alt="image" src="https://github.com/ChunelFeng/CGraph/assets/37905059/5609ea7b-9ced-49ed-9cbd-166242d9c9d9">

你好，我们提供的demo中，其实就是在创建节点（registerGElement） 的时候，指定父节点关系的哈（第二个参数，{} 中的内容）

如果您提到的是 pipeline->registerGElement<MyNode1>(&a, {}, "nodeA");   中的  &a 能否省略，个人不建议。
因为这样的话，可以将所有element的生产和释放流程，托管到色图框架中，而不需要外部做管理。
或者说，也不允许外部做任何管理和改动（比如删除）

这样的优势，是用户在使用的过程中，并不感知相关内容，并且也省去了维护（比如自行释放）的成本。
但是 a 这个node指针变量，又一定要存在，因为后面的 例子中，还会通过 a->setXXX() 等方式，
做一些配置信息

**Comment by kkonghao** [comment]
您的意思是在创建Node的时候是可以指定节点依赖关系的么？如下面的MyNode2 类下的伪代码 void config()函数中的内容
```c++
class MyNode1 : public CGraph::GNode {
public:
    CStatus run() override
    {
        CStatus status;
        printf("[%s], Sleep for 1 second ...\n", this->getName().c_str());
        CGRAPH_SLEEP_SECOND(1)
            return status;
    }
};

class MyNode2 : public CGraph::GNode {
public:

    void config()
    {
        this.set_parent(MyNode1);
        this.set_name("MyNode2");
    }


    CStatus run() override
    {
        CStatus status;
        printf("[%s], Sleep for 2 second ...\n", this->getName().c_str());
        CGRAPH_SLEEP_SECOND(2)
            return status;
    }
};

```

**Comment by ChunelFeng** [comment]
您说的 this.set_parent(MyNode1);  这个，主要是指将 a 作为 b 的父节点对吧。
如果 在b构建的时候，a已经被new过了，是可以通过  addDependGElements 函数来实现这个功能的。
但，实际使用的过程中，我们强烈不建议这样使用

**Comment by kkonghao** [comment]
> 您说的 this.set_parent(MyNode1); 这个，主要是指将 a 作为 b 的父节点对吧。 如果 在b构建的时候，a已经被new过了，是可以通过 addDependGElements 函数来实现这个功能的。 但，实际使用的过程中，我们强烈不建议这样使用

感谢，实际中是有这样的需求的，如果我有n个算子，下个算子依赖上个算子计算的结果或者上个算子并行的几个算子的计算结果，pipline那里要写很长一大串，如果有方法能自动执行就好了

**Comment by ChunelFeng** [comment]
您好，如果“刚开始并不知道执行什么，而是根据之前计算的结果来决定”，    非常推荐您试试看色图的 condition和 multi condition的功能。 

如果对色图有兴趣，欢迎添加我个人微信(ChunelFeng)，我们很想听取和了解大家需要什么样的功能，并且基于此做一些通用优化。也很乐意提供一些相关的色图的解决方案和思路

**Comment by ChunelFeng** [comment]
参考视频信息：

https://www.bilibili.com/video/BV1wh4y1s7CZ/?spm_id_from=333.337.search-card.all.click&vd_source=2c7baed805c6cb33d630d5d4546cf0be

https://www.bilibili.com/video/BV1ic411n7d1/?spm_id_from=333.337.search-card.all.click&vd_source=2c7baed805c6cb33d630d5d4546cf0be
