### ISSUE TITLE
资源互斥场景

### ISSUE THREAD

**Issue by Codesire-Deng** [ChunelFeng/CGraph#18]
您好，并行计算有时会出现一些需要互斥锁的场景，例如多个并行Node之间共享了一个优先队列。此时朴素的做法是给数据结构加互斥锁。针对这种需求，在 CGraph 中，请问：
1. 能否通过设计更好的 Graph 来规避加锁；若能，这种设计能否通用？
2. 如果必须要加互斥锁，CGraph 有没有对应的工具；是否可以使用`std::mutex`？

谢谢！

**Comment by ChunelFeng** [comment]
您好，很高兴跟你一起讨论。

**Comment by ChunelFeng** [comment]
您好，很高兴和你一起讨论这个问题。

* 1，加锁的过程在node中自定义实现。非并发的节点中，使用同一个队列，理论上不需要加锁的。如果有类似 pub+sub的需求，将节点分拆，并在pipeline中设定成有先后依赖关系（非并发）的情况，此为上策。

* 2，如果无法避免在并发逻辑中，使用到同一个队列，CGraph在参数中，提供了读写互斥机制，并对外封装统一语义。将队列通过 GParam的方式，在n个并发的节点中进行传递，并且通过 `CGRAPH_PARAM_WRITE_CODE_BLOCK`、`CGRAPH_PARAM_READ_CODE_BLOCK` 的方式，可以确保 只读/读写 安全。

参考这个demo：https://github.com/ChunelFeng/CGraph/blob/main/tutorial/MyGNode/MyWriteParamNode.h   ，可以理解成 myParam这个参数中，包含了一个被并发使用的任务队列。在包含 CGRAPH_PARAM_WRITE_CODE_BLOCK(myParam) 的代码块中，可以确保 读写安全。

**Comment by Codesire-Deng** [comment]
谢谢！我想我理解了😄
