### ISSUE TITLE
perf 精度考虑从 ms 改为 us

### ISSUE THREAD

**Issue by baoguo-ma1** [ChunelFeng/CGraph#184]
ms 看不出两个 node 之间的时延。

**Comment by ChunelFeng** [comment]
您好，已经在最新榜单版本中，完成了对应的改动，对应的单位仍为ms，但是添加了小数部分。

![image](https://github.com/ChunelFeng/CGraph/assets/37905059/fd0aed21-eb05-4046-bc56-951c6cacb25a)
