### ISSUE TITLE
关于GPipeline::registerGElement的逻辑

### ISSUE THREAD

**Issue by wxjhll** [ChunelFeng/CGraph#196]
template<typename T,
        c_enable_if_t<std::is_base_of<GElement, T>::value, int>>
CStatus GPipeline::registerGElement(GElementPtr *elementRef,
                                    const GElementPtrSet &dependElements,
                                    const std::string &name,
                                    CSize loop) {
    CGRAPH_FUNCTION_BEGIN
    CGRAPH_ASSERT_INIT(false)

    if (std::is_base_of<GGroup, T>::value) {
        /**
         * 如果是GGroup类型的信息，则：
         * 1，必须外部创建
         * 2，未被注册到其他的pipeline中
         */
        if ((*elementRef) != nullptr
            && ((GGroupPtr)(*elementRef))->isRegistered()) {
            CGRAPH_RETURN_ERROR_STATUS("this group register duplicate")
        }
    } else if (std::is_base_of<GNode, T>::value || std::is_base_of<GAdapter, T>::value) {
        /**
         * 如果不是group信息的话，且属于element（包含node和adapter）
         * 则直接内部创建该信息
         */
        (*elementRef) = new(std::nothrow) T();
    }

    CGRAPH_ASSERT_NOT_NULL(*elementRef)
    status = (*elementRef)->setElementInfo(dependElements, name, loop,
                                           this->param_manager_,
                                           this->event_manager_);
    CGRAPH_FUNCTION_CHECK_STATUS

    status = element_manager_->add(dynamic_cast<GElementPtr>(*elementRef));
    CGRAPH_FUNCTION_CHECK_STATUS
    repository_.insert(*elementRef);
    CGRAPH_FUNCTION_END
}

 status = element_manager_->add(dynamic_cast<GElementPtr>(*elementRef));
 repository_.insert(*elementRef);
在cerateGNode和createGGroup中执行了 repository_.insert(*elementRef);在registerGElement中又再一次执行了 repository_.insert(*elementRef)。是不是重复添加了。GElementRepository这个类的作用是什么，感觉和GElementManager有点类似，在pipeline的init()中，GElementManager执行了init(),element->cur_state_ = GElementState::NORMAL;，在pipeline的run中GElementRepository执行setup():status = pushAllState(GElementState::NORMAL),这两处都对element的cur_state_ 修改了感觉重复了。

**Comment by ChunelFeng** [comment]
你好，上面提到的，应该是两个问题了，哈哈，我分两条来回答一下吧。第一个问题，是pipeline中的 repository_ 和 element_manager_ 中的内容，有何异同，是否重复添加了。

这两个对象中的内容是不一样的。 repository_ 中包含了所有 element（包含 node和 group）的内容。
element_manager_ 中的内容，是表明注册到 pipeline 中的信息，这就 **不包含** 在 group 中的node或者group了。
因为是纯指针的添加，所以几乎不会影响内存大小。

element_manager_ 的设计 是为了pipeline 方便实现执行管控。
也就是说，pipeline执行的时候，仅需要执行这里的内容就可以了，而不需要再关心当 element为 group的情况下，如何执行。
而真当 element是 group的时候，仅需要执行 当前group内部的逻辑即可。

而 repository_ 的设计，是为了外部对其中的所有element进行统一设定使用。
比如，pipeline 析构的时候，要 delete其中所有的 element，
只要for repository_，并且 delete element，就好了。
就不需要每个 group 来管控内部节点的析构了

同样，您也可以类比 所有element 设置State的操作。

**Comment by ChunelFeng** [comment]
关于 element->cur_state_ 被重复赋值的问题，我们看了一下，的确存在类似的情况。
之所以 在 init的时候，赋值一遍，又在 run()开始的时候 赋值一遍，

主要是因为 run() 方法是可以多次反复执行的。
可能出现 init -> run -> cancel -> run -> destroy 的调用逻辑，
故 run 开始的时候，可能会存在 状态为 cancel的情况。需要在 开始执行的时候，统一恢复一波状态。
当然了， pushAllState 方法中，也有判断是否重复设定的机制，尽可能的避免了多次重复赋值的影响。

**Comment by wxjhll** [comment]
非常感谢，明白了

**Comment by wxjhll** [comment]
> 关于 element->cur_state_ 被重复赋值的问题，我们看了一下，的确存在类似的情况。
> 之所以 在 init的时候，赋值一遍，又在 run()开始的时候 赋值一遍，
> 
> 主要是因为 run() 方法是可以多次反复执行的。
> 可能出现 init -> run -> cancel -> run -> destroy 的调用逻辑，
> 故 run 开始的时候，可能会存在 状态为 cancel的情况。需要在 开始执行的时候，统一恢复一波状态。
> 当然了， pushAllState 方法中，也有判断是否重复设定的机制，尽可能的避免了多次重复赋值的影响。
> 
> 
> 

非常感谢，明白了

**Comment by ChunelFeng** [comment]
哈哈，感觉老哥看的非常细哈。有些地方，的确是我们考虑的不够周全，
也有些地方，可能是因为后期改版啥的，部分连带修改没跟上。
欢迎随时交流和指教。


还有，就是系那个问一下，您们看色图的逻辑，
是考虑落地使用，还是纯了解一下实现思路？

**Comment by wxjhll** [comment]
> 

还没工作，目前在学习C++，之前为了学习线程池，发现的这个项目，文档写的挺全的，就学习下。

**Comment by wxjhll** [comment]
> 哈哈，感觉老哥看的非常细哈。有些地方，的确是我们考虑的不够周全， 也有些地方，可能是因为后期改版啥的，部分连带修改没跟上。 欢迎随时交流和指教。
> 
> 还有，就是专门问一下，您们看色图的逻辑， 是考虑落地使用，还是纯了解一下实现思路？

还没工作，目前在学习C++，之前为了学习线程池，发现的这个项目，文档写的挺全的，就学习下。

**Comment by ChunelFeng** [comment]
哈哈，感谢您的支持。也欢迎给我们b站的视频，一键三连。
随时交流，多多指教
