### ISSUE TITLE
BigBool 存在的意义是什么？

### ISSUE THREAD

**Issue by baoguo-ma1** [ChunelFeng/CGraph#199]
我只在 Chromium 的源码中看见过 BigBool，我觉得代码中不要存在缺乏普适性的内容。

**Comment by ChunelFeng** [comment]
是这样的，我们设置这个，是为了替代bool 类型，避免 bool 变量造成的字节不对齐，从而可能引发的一点问题。
因为之前有代码的历史包袱，后期没有用起来。

如果基于色图做二次开发的话，可以考虑用这个变量，来定义一个 enable 的变量
