### ISSUE TITLE
CObject 本身改为不可 run，CRunObject 继承 CObject 并可 run

### ISSUE THREAD

**Issue by baoguo-ma1** [ChunelFeng/CGraph#200]
代码里有一些 FooManager 类，却继承 FooObject 类，但代码逻辑上 FooManager 又不会嵌套。
例如 FooManager : public FooObject 可以改为 FooManager : public BarObject, public CDescInfo。
另外 FooObject 不继承 CRunObject，改为继承 CObject，这样就不需要实现 run 为 NOT_SUPPORT。

**Comment by ChunelFeng** [comment]
设计方面的内容，很难评定好坏，或者说，从各个角度来看，都有适合和不适合的地方。
暂时不准备修改这一块内容，但也非常感谢您的意见。
