### ISSUE TITLE
GPipelineFactory生成pipeline能否复用？

### ISSUE THREAD

**Issue by Lowpower** [ChunelFeng/CGraph#253]
我在执行第二次pipeline的时候会core dump
    /* 创建一个流水线，用于设定和执行流图信息 */
    CGraph::GPipelinePtr pipeline = CGraph::GPipelineFactory::create();
    CGraph::GElementPtr a, b = nullptr;
    /* 注册节点之间的依赖关系 */
    pipeline->registerGElement<ContentEmbedding>(&a, {}, "ContentEmbedding");
    pipeline->registerGElement<LongMemory>(&b, {a}, "LongMemory");
    pipeline->createGParam<ContextParam>(ContextParam::GetName());
    pipeline->createGParam<EmbeddingParam>(EmbeddingParam::GetName());
    pipeline->createGParam<ResponseParam>(ResponseParam::GetName());
    pipeline->dump();

**Comment by Lowpower** [comment]
第二次调用的时候param就变成空指针了

**Comment by ChunelFeng** [comment]
您好，我不是非常确定您那边遇到了什么问题，但至少能确定，下面这句话，是错误的
```cpp
pipeline->createGParam(ResponseParam::GetName());
```

我解释一下 `GPipelineFactory::create()` 原理：
函数 每次返回，都是一个独立的 pipeline，跟上次调用不会重复。
您可以对这个pipeline 的实例，注册算子，创建参数（参数在pipeline 内部共享）。
不同的pipeline中，算子和参数都是独立且互不影响的。

pipeline执行结束的时候，请使用 GPipelineFactory::remove(pipeline) 将其完全释放

**Comment by Lowpower** [comment]
pipeline是不能复用的吗？如果我在pipeline执行结束的时候不去remove，下次请求从头执行这个pipeline会有什么问题？

**Comment by ChunelFeng** [comment]
我想，我应该理解您的问题了。

是这样的，您在 pipeline这一层注册的 GParam参数， 在 pipeline->destroy()的时候，会被全部析构掉的。
如果这个时候，你直接 pipeline->init() 的时候，这个情况下，pipeline内部实际上是没有刚开始注册 GParam的。

两个思路：
1，实现一个 prepareNode，将所有的 GParam的注册函数，放在它的 init()方法中。然后将它注册到 pipeline的开头。这样 就可以反复 init 和 destroy，而不需要重新生成 pipeline 了

2，每次 pipeline->init 之前，都重新注册一遍你需要的那些GParam信息，然后再init。 PS：项目内部支持**同名且同类型**的 GParam 多次调用接口注册，且默认为仅注册一次的效果。

**Comment by ChunelFeng** [comment]
HI，你好，想来回访一下，是否已经开始投入使用。
是否有什么意见和建议

**Comment by Lowpower** [comment]
我这里按第二种思路去实现了

**Comment by ChunelFeng** [comment]
很高兴听到您已经pass这个问题的消息，看您的个人git信息，您是来自tx的程序员，
我们小团队很重视这一次色丶图项目在tx实际项目中的落地情况，

如果您对 项目使用、功能和未来的发展方向 有兴趣，随时欢迎您添加我的个人微信 （ChunelFeng），一起交流分享和学习。
很期待您分享你们的使用场景，落地思路和使用方式。我们可能也能提供一些意见和建议，和之前的一些踩坑记录。
我们也想很想把这次在tx的实际落地，打造成一个标杆项目，作为今后推广的背书。

btw，色丶图昨天发布了新的版本（v2.5.2），功能和性能都有了较大幅度的提升，可以考虑升级。
再次期待和您取得联系
