### ISSUE TITLE
纯老师，您是怎么过 momenta 面试，并拿到 200w 年薪的

### ISSUE THREAD

**Issue by Codesire-Deng** [ChunelFeng/CGraph#265]
有钱一起赚 （狗头🐶）

https://github.com/ChunelFeng/CGraph/blob/58cc4f42f5639c71c3b4ececbcc14a5b55e9a80b/src/CBasic/CStatus.h#L58-L66

**Comment by ChunelFeng** [comment]
这位朋友，你是对 momenta有什么误会，还是对 200w有什么误会 ？？？

**Comment by Bridge1127** [comment]
> 这位朋友，你是对 momenta有什么误会，还是对 200w有什么误会 ？？？
批注，我对MMT没误会，对200万也没误会，但就是对批猪的200W有误会

**Comment by ChunelFeng** [comment]
> > 这位朋友，你是对 momenta有什么误会，还是对 200w有什么误会 ？？？
> > 批猪，我对MMT没误会，对200万也没误会，但就是对批猪的200W有误会

别闹，不要听风神瞎说
