### ISSUE TITLE
序列化和反序列化Pipline的功能

### ISSUE THREAD

**Issue by beichen2012** [ChunelFeng/CGraph#279]
请问有无序列化一个pipline到二进制，并能从二进制恢复这个pipline的功能？

**Comment by beichen2012** [comment]
感谢您的耐心回答，您的想法非常全面。包含这个pipline（图）和各个节点的信息(param）两个方面，序列化时，将图及节点信息、参数等保存至文件（比如pytorch的 save to checkpoint），反序列化时，从这些二进制，能直接恢复出pipline及各个节点的信息、参数，直接可以运行run。
使用场景比如我们配置了一个运行图（如流程图、算法计算网络），保存下来后，可以网络分发或是本地存储后切换不同的流程、计算网络等。
序列化组件 ，是否考虑引入json.hpp这样无任何其他依赖或是一些纯头文件的优秀三方项目？做成可选的编译配置项，也不会对当前库的编译使用造成负担。（PS：这个库拉下来，直接vs打开就可以run了，非常nice，哈哈）
再次感谢您的耐心回答。

**Comment by ChunelFeng** [comment]
哈哈，再确认一下，您是直接 git clone setu.git 到本地，然后vs打开的，
还是 download 项目到本地，然后用 vs打开的捏？

**Comment by beichen2012** [comment]
download zip 到本地。vs2022直接找开运行。

**Comment by libaineu2004** [comment]
> > > 请问有无序列化一个pipline到二进制，并能从二进制恢复这个pipline的功能？
> > 
> > 
> > 请问这个功能现在实现了吗？
> 
> 你好，cpp版本一直没有做序列化功能，纯cpp 不包含三方库的话，的确不是很好做这个。
> 
> 同时，我们提供了 python版本，如果做序列化的话，用 py版本应该比较方便

使用json文件来做持久化可以不？
有个轻量级的json解析库
https://github.com/nlohmann/json
