### ISSUE TITLE
部分流程禁用

### ISSUE THREAD

**Issue by beichen2012** [ChunelFeng/CGraph#280]
请问下是否支持部分流程禁用功能，如：A->B->C的流程。将B禁用后，B及其后续 的C在run时均直接不参与run（但参数的reset还是参与的）这样的功能？使用场景是，比如有一个流程，在某处分成两个（或多个）分支， 在某一时刻，只想运行某一个分支，另一个分支不想让他运行了。
这样，当前是否可以使用增加一个条件判断的节点来实现？
或后续您是否有考虑增加禁用功能？如使用某特定的节点或常规节点实现disable功能？

**Comment by ChunelFeng** [comment]
整体看下来，方法还是有好几种的。
比如，通过 setVisible的方式，或者通过 multiCondition的方式，
或者通过自定义 param解析逻辑的方式。

欢迎体验尝试

**Comment by beichen2012** [comment]
Pretty Good
