### ISSUE TITLE
实现动态构图的功能

### ISSUE THREAD

**Issue by Lowpower** [ChunelFeng/CGraph#283]
例如我提供如下的graph的定义（图中的node是已经提前定义好的）
digraph CGraph {
compound=true;
A[label="A"];
A -> B;
A -> C;
B[label="B"];
B -> D;
C[label="C"];
C -> D;
D[label="D"];
}
生成这样的执行图
<img width="509" alt="image" src="https://github.com/ChunelFeng/CGraph/assets/3133734/f2c0d11b-aee4-48bb-9a31-5976a2703917">

**Comment by ChunelFeng** [comment]
请参考 feat/mutable 分支中的逻辑：https://github.com/ChunelFeng/CGraph/blob/feat%2Fmutable/tutorial/T26-GMutable.cpp

看一下，这个功能，是不是您想要的

**Comment by ChunelFeng** [comment]
你好，提供了mutable 功能，支持在运行过程中，随时修改依赖关系，执行次数信息。跪求star

https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T26-Mutable.cpp

**Comment by Lowpower** [comment]
你会错意了，我要的是动态构图，而不是静态图动态执行，比如说我有100个node，我在运行过程中会取1-N个node去构图，node也可能会复用

**Comment by Lowpower** [comment]
pipeline->registerGElement<MyNode1>(&a, {}, "nodeA", 1);
    pipeline->registerGGroup(&b_mutable, {a}, "mutableB", 1);
    pipeline->registerGElement<MyNode2>(&c, {a}, "nodeC", 1);
    pipeline->registerGElement<MyWriteParamNode>(&d, {b_mutable, c}, "nodeD", 1);
这段代码还是框死了我的图结构

**Comment by ChunelFeng** [comment]
你把你所有的node，都放到 mutable里，不就不框死了么
