### ISSUE TITLE
循环逻辑 和参数相关使用问题

### ISSUE THREAD

**Issue by mmtxcp** [ChunelFeng/CGraph#288]
1、CGraph 中 循环逻辑 目前可以指定循环次数，是否能获取当前正在执行的迭代？
2、循环迭代的应用场景：例如对一个目录下的多文件进行处理，比如格式转换，坐标转换，后续可能还会跟着其他node， 迭代器是作为独立的node，文件处理也是个节点，那么这个过程是可以并行的，针对这个场景，需要如何使用CGraph？使用GMessageParam是否能满足？
3、CGraph中是否只能对element 添加参数？是否能在pipeline 中添加独立的参数？场景：GIS行业里的地理处理模型中，有个独立参数的概念，即可以在处理模型中添加独立参数（例如数据源），算子节点的参数可以连接独立参数，作为数据来源。（当前变通的方式可以做个node，专门用来获取数据，输出参数是数据源，然后在用参数进行连接）
![image](https://github.com/ChunelFeng/CGraph/assets/17898475/907b807d-abe4-4f5e-b128-fb50574b69c1)要素类是个独立参数，通过连接都把算子节点中的参数隐藏了，实际上独立参数可以连接很多算子，可以作为很多算子的输入参数。

**Comment by mmtxcp** [comment]
pipeline是否可以动态插入element ？

**Comment by ChunelFeng** [comment]
【迭代器是作为独立的node，文件处理也是个节点】   
针对这句话，迭代器的step by step 的迭代，和 文件处理，都是相对比较耗时的操作么？
我的理解，迭代器应该是很快的操作，文件处理应该是比较耗时的操作

**Comment by ChunelFeng** [comment]
> pipeline是否可以动态插入element ？

可以尝试 通过 node 中的 spawn()
