### ISSUE TITLE
请教一下线程池的测试

### ISSUE THREAD

**Issue by SpencerChou** [ChunelFeng/CGraph#29]
你好，想测一下线程池的性能，想使用一下线程池，是不是 也先把整个CGraph make下来就行啊，或者说 我用您的那个镜像进去测试，直接include线程池相关就可以进行测试了嘛

**Comment by SpencerChou** [comment]
还有就是 如何做整体的异步的线程池的测试的呀，从您的博客过来
http://www.chunel.cn/archives/cgraph-threadpool-5-introduce
我也想做一个线程池和传统线程池的优化测试看一看，但是没太想好这个测试方案应该是怎么去实现的

**Comment by ChunelFeng** [comment]
您好，感谢您的关注。 项目本身无任何三方依赖，也支持 mac（我的开发机）， linux和 win平台，通过ide（推荐clion，vs也可以） 即可运行。
如果单独运行线程池的话，这里有个 小例子，可以看看：https://github.com/ChunelFeng/CGraph/blob/main/tutorial/TU01-ThreadPool.cpp

有任何问题或者意见，请加我微信（ChunelFeng），以便随时交流。

**Comment by ChunelFeng** [comment]
> 还有就是 如何做整体的异步的线程池的测试的呀，从您的博客过来 http://www.chunel.cn/archives/cgraph-threadpool-5-introduce 我也想做一个线程池和传统线程池的优化测试看一看，但是没太想好这个测试方案应该是怎么去实现的

我在博客中，给出的例子，就是 往CGraph的 线程池中，大量并发的扔 return 0 的任务。 跟github上，其他的线程池实现进行耗时对比。

**Comment by ChunelFeng** [comment]
> 

Hi，请问 效果怎样，可以跑起来，并且测试了吗

**Comment by SpencerChou** [comment]
您好，我对测试的方案实施还是有没有想明白的地方，就是说 比如我想同时塞不同数量的任务进入线程池，然后测试响应时间。这种情况下，我比如同时塞5个任务，塞10个任务……一直到同时塞100个任务，然后计算响应时间，画折线图来体现线程池对比的性能，是要求平均响应时间吗？

**Comment by SpencerChou** [comment]
这之中并发数和执行次数分别是啥定义呀
![image](https://user-images.githubusercontent.com/34341763/212560005-f75a4539-d136-4784-8d4f-f11020a80155.png)

**Comment by SpencerChou** [comment]
再看一些线程池优化论文的时候，看他们实验有这样一种实验，一直没搞懂怎么计算的。。是计算每个任务的时间然后求平均数。。还是response time是整体任务完成的计算时间。。纵坐标response time，横坐标request rate，或者是什么request的数量还是啥的
![image](https://user-images.githubusercontent.com/34341763/212715517-3c1f0553-f03a-4aab-923d-8a8615b293df.png)

这种实验以您做的实验为参考，就是说执行次数，从1到500，依次计算总耗时，然后画图嘛。。

然后就是 这个并发数，是 又开了x（并发数）路线程，来请求CGraph的线程池嘛

**Comment by ChunelFeng** [comment]
> 然后就是 这个并发数，是 又开了x（并发数）路线程，来请求CGraph的线程池嘛

我就是这样测的，不确定论文中是否也是相同
