### ISSUE TITLE
一次构图，多次并发注入param执行的情况下会coredump

### ISSUE THREAD

**Issue by Lowpower** [ChunelFeng/CGraph#293]

**Comment by Lowpower** [comment]
执行run的时候加锁保证串行才能正常

**Comment by Lowpower** [comment]
否则会有内存踩坏的问题

**Comment by ChunelFeng** [comment]
哈哈，看现象，应该是您在 run() 的方法中，反复调用 createGParam<T>(key) 这个方法了是吧。
这个内部的原理，是你在调用这个接口的时候，实际上反复往一个 指针上写值。

我们推荐，在pipeline init之前，或者在 node init 的时候，进行参数注册。
针对您提到的这个问题，我们后期的版本中，会考虑加入机制，确保并发 createGParam的时候也ok

**Comment by ChunelFeng** [comment]
我看了一下代码，您并发的在node的 run()的方法中，createGParam 是没有问题的。
并发的在node的 run()方法中，getGParam也是没有问题的。

但是，并发的 create + get，应该是可能会问题的。
我们本来的设想是，所有的 param，均在 init()的时候，设置完毕。
针对您这种使用情况，请切换到当前最新的 main 分支，应该就ok了，也不需要在外部加锁来保护了

**Comment by Lowpower** [comment]
我们的需求只有两种实现方式，要么动态构图。包括createGParam，但是目前无法实现这样的使用方式，所以我用的是第二种方式，静态构图，每次请求来了createGParam，也就是生成新的param注入到图里去执行，但是目前来看，静态图并发执行的过程中GParam并没有被保护

**Comment by Lowpower** [comment]
试用了最新版，还是有问题

**Comment by Lowpower** [comment]
期望的形式：
两种实现方法：
1 每次的graph都是新create出来的，但是Element是期望可以复用，而不是每次register的时候隐式构造新的（Element初始化化有很重的负载）
2 服务启动是graph构造好不动了，每次run的时候期望保护createGParam里的内容，并发执行时不要有race

**Comment by ChunelFeng** [comment]
能否提供最小验证版本，我这边尝试一下

**Comment by ChunelFeng** [comment]
您好，来确认一下，是否已经解决？
