### ISSUE TITLE
CPU占用问题

### ISSUE THREAD

**Issue by RunCodeFly** [ChunelFeng/CGraph#299]
关于CPU占用过高问题，下面是我dump的信息：
digraph CGraph {
compound=true;
p000001E62A675750[label="12"];
p000001E636118820[label="4"];
p000001E636118A90[label="3"];
p000001E636118A90 -> p000001E6361191E0;
p000001E636118D00[label="6"];
p000001E636118D00 -> p000001E63611ACB0;
p000001E6361191E0[label="8"];
p000001E6361191E0 -> p000001E62A675750;
p000001E636119BA0[label="7"];
p000001E636119BA0 -> p000001E63611B670;
p000001E63611A080[label="5"];
p000001E63611A080 -> p000001E63611B400;
p000001E63611ACB0[label="10"];
p000001E63611B400[label="9"];
p000001E63611B670[label="11"];
p000001E63611B8E0[label="0"];
p000001E63611B8E0 -> p000001E636118D00;
p000001E63611B8E0 -> p000001E636119BA0;
p000001E63611BB50[label="2"];
p000001E63611BB50 -> p000001E636118820;
p000001E63611BB50 -> p000001E63611A080;
p000001E636420F30[label="13"];
p000001E636420F30 -> p000001E636118A90;
p000001E636420F30 -> p000001E63611B8E0;
p000001E636420F30 -> p000001E63611BB50;
}

下面是我的线程池配置的代码 ：
**
 * 以下为线程池配置信息
 */
static const int CGRAPH_DEFAULT_THREAD_SIZE = 0;                                            // 默认开启主线程个数
static const int CGRAPH_SECONDARY_THREAD_SIZE = 8;                                          // 默认开启辅助线程个数
static const int CGRAPH_MAX_THREAD_SIZE = 16;                                               // 最大线程个数
static const int CGRAPH_MAX_TASK_STEAL_RANGE = 2;                                           // 盗取机制相邻范围
static const bool CGRAPH_BATCH_TASK_ENABLE = false;                                         // 是否开启批量任务功能
static const int CGRAPH_MAX_LOCAL_BATCH_SIZE = 2;                                           // 批量执行本地任务最大值
static const int CGRAPH_MAX_POOL_BATCH_SIZE = 2;                                            // 批量执行通用任务最大值
static const int CGRAPH_MAX_STEAL_BATCH_SIZE = 2;                                           // 批量盗取任务最大值
static const int CGRAPH_PRIMARY_THREAD_BUSY_EPOCH = 10;                                     // 主线程进入wait状态的轮数，数值越大，理论性能越高，但空转可能性也越大
static const CMSec CGRAPH_PRIMARY_THREAD_EMPTY_INTERVAL = 3;                                // 主线程进入休眠状态的默认时间
static const CSec CGRAPH_SECONDARY_THREAD_TTL = 10;                                         // 辅助线程ttl，单位为s
static const bool CGRAPH_MONITOR_ENABLE = false;                                            // 是否开启监控程序
static const CSec CGRAPH_MONITOR_SPAN = 5;                                                  // 监控线程执行间隔，单位为s
static const CMSec CGRAPH_QUEUE_EMPTY_INTERVAL = 3;                                         // 队列为空时，等待的时间。仅针对辅助线程，单位为ms
static const bool CGRAPH_BIND_CPU_ENABLE = false;                                           // 是否开启绑定cpu模式（仅针对主线程）
static const int CGRAPH_PRIMARY_THREAD_POLICY = CGRAPH_THREAD_SCHED_OTHER;                  // 主线程调度策略
static const int CGRAPH_SECONDARY_THREAD_POLICY = CGRAPH_THREAD_SCHED_OTHER;                // 辅助线程调度策略
static const int CGRAPH_PRIMARY_THREAD_PRIORITY = CGRAPH_THREAD_MIN_PRIORITY;               // 主线程调度优先级（取值范围0~99，配合调度策略一起使用，不建议不了解相关内容的童鞋做修改）
static const int CGRAPH_SECONDARY_THREAD_PRIORITY = CGRAPH_THREAD_MIN_PRIORITY;             // 辅助线程调度优先级（同上）

跑起来后CPU整个快到100%，大佬求助降CPU方法

**Comment by ChunelFeng** [comment]
你好，感觉整体配置没啥问题。我给出一个推荐的信息：

```cpp
static const int CGRAPH_DEFAULT_THREAD_SIZE = 8; // 默认开启主线程个数
static const int CGRAPH_SECONDARY_THREAD_SIZE = 0; // 默认开启辅助线程个数
static const int CGRAPH_MAX_THREAD_SIZE = 8; // 最大线程个数
static const int CGRAPH_PRIMARY_THREAD_BUSY_EPOCH = 2; // 主线程进入wait状态的轮数，数值越大，理论性能越高，但空转可能性也越大
static const CMSec CGRAPH_PRIMARY_THREAD_EMPTY_INTERVAL = 30; // 主线程进入休眠状态的默认时间
```

如果 cpu仍占用过高，建议通过 perf 方法，打印出来当前node的耗时信息

**Comment by ChunelFeng** [comment]
已经解决，mark一下
