### ISSUE TITLE
T00-HelloWorld执行时出现run failed...

### ISSUE THREAD

**Issue by christsun** [ChunelFeng/CGraph#3]
我在x86 ubuntu 16.04上使用clang++编译得到二进制T00-HelloWorld，很大概率出现执行后出现：
./T00-HelloWorld
hello, world.
[CGraph] [2021-08-20 16:30:13.431] thread [140105641174784] run failed...

看起来是UThreadPrimary调用run()时成员pool_threads_存在空指针的情况。
pipeline->process()内部会调用deinit，从而释放了threadpool；之后threadpool的线程再调度回来的时候执行run发现threadpool中的UThreadPrimary指针已经为空了。

**Comment by ChunelFeng** [comment]
抱歉带来不好的体验。
描述问题本地（mac 和 ubuntu v20.04）多次尝试，不出现。
方便的话请加我微信（ChunelFeng，或者是扫readme文件下方二维码）
我们一起来看一下哈。

**Comment by ChunelFeng** [comment]
fix it
