### ISSUE TITLE
Does the project have any tests?

### ISSUE THREAD

**Issue by MaxBrain** [ChunelFeng/CGraph#30]
Does the project have any tests?
If not, what are the plans?

**Comment by ChunelFeng** [comment]
not yet.  but we have many tutorial.cpp , which can help you know this repo quickly.
ex:  https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T00-HelloCGraph.cpp

**Comment by MaxBrain** [comment]
Can I try to write tests for this project?

**Comment by ChunelFeng** [comment]
it is warm welcomed.
better make a test dir, with googel test.

**Comment by ChunelFeng** [comment]
HI, friend, what is going on?  Nice to get in touch with you. 

I am from China. Please let me know where are you come from.

And, can you please give me a brief view for your plan, and your idea ?

If you have any question, feel free to get in touch with us, thank you .
