### ISSUE TITLE
addEParam能不能把传参改成智能指针

### ISSUE THREAD

**Issue by Lowpower** [ChunelFeng/CGraph#302]
我就简单传个int，还得这么写？
class GIntParam : public CGraph::GPassedParam {
public:
    explicit GIntParam(int value) : value_(value) {}
    GIntParam() : value_(0) {}

    void clone(CGraph::GPassedParam* param) override {
        if (auto p = dynamic_cast<GIntParam*>(param)) {
            value_ = p->value_;
        }
    }
    int value_;
};

**Comment by Lowpower** [comment]
这样我就不用实现那个clone方法了，有些参数可以自己去管理自己内部数据

**Comment by ChunelFeng** [comment]
您好，ElementParam 主要负责用于一次性传递多个参数的情况。

针对您这种仅需传入个别参数的情况，我们推荐使用模板节点来进行构造。

请参考视频中的介绍信息：

https://www.bilibili.com/video/BV1jX4y1z7fB/?spm_id_from=333.788&vd_source=2c7baed805c6cb33d630d5d4546cf0be

**Comment by ChunelFeng** [comment]
智能指针的这个方案，是一种优化的思路，我们接下来会考虑具体实现。
感谢您的意见
