### ISSUE TITLE
关于节点返回错误导致崩溃的一个bug

### ISSUE THREAD

**Issue by yaowenxin** [ChunelFeng/CGraph#305]
并行运行的节点，都返回错误时，会发生崩溃现象。
描述如下：节点A同时流入B、C，B和C都返回错误，C先返回（运行时间1秒），B后返回（运行时间3秒），节点C返回错误时，pipeline的run函数就返回了，然后进入到destroy()函数，并阻塞在那里，然后等到B返回时，就会发生崩溃现象。

下面是修改过的T01-Simple.cpp，用于复现上述现象。

#include "MyGNode/MyNode1.h"
#include "MyGNode/MyNode2.h"

using namespace CGraph;

std::recursive_mutex s_node_mutex;

class SimpleNodeA : public CGraph::GNode {
public:
    CStatus run () override {
        CStatus status;
        CGraph::CGRAPH_ECHO("[%s], enter SimpleNode-A run function. Sleep for 1 second ... ", this->getName().c_str());
        CGRAPH_SLEEP_SECOND(1);
        return status;
    }
};

class SimpleNodeB : public CGraph::GNode {
public:
    CStatus run () override {
        CStatus status;
        CGraph::CGRAPH_ECHO("[%s], enter SimpleNode-B run function. Sleep for 3 second ... ", this->getName().c_str());
        //std::unique_lock<std::recursive_mutex> lock(s_node_mutex);
        CGRAPH_SLEEP_SECOND(3);             
        status = CStatus(-1, "error - B");
        CGraph::CGRAPH_ECHO("[%s], leave SimpleNode-B", this->getName().c_str());
        return status;
    }
};

class SimpleNodeC : public CGraph::GNode {
public:
    CStatus run () override {
        CStatus status;
        CGraph::CGRAPH_ECHO("[%s], enter SimpleNode-C run function. Sleep for 1 second ... ", this->getName().c_str());
        //std::unique_lock<std::recursive_mutex> lock(s_node_mutex);
        CGRAPH_SLEEP_SECOND(1);
        status = CStatus(-1, "error - C");
        CGraph::CGRAPH_ECHO("[%s], leave SimpleNode-C", this->getName().c_str());
        return status;
    }
};

class SimpleNodeD : public CGraph::GNode {
public:
    CStatus run () override {
        CStatus status;
        CGraph::CGRAPH_ECHO("[%s], enter SimpleNodeD run function. Sleep for 1 second ... ", this->getName().c_str());
        CGRAPH_SLEEP_SECOND(1);
        return status;
    }
};

void tutorial_simple() {
    /* 创建图对应的pipeline */
    GPipelinePtr pipeline = GPipelineFactory::create();

    /* 定义GElementPtr类型的变量 */
    GElementPtr a, b, c, d = nullptr;

    /**
     * 注册节点，其中MyNode1和MyNode2必须为GNode的子类，否则无法通过编译。
     * status+= 操作，可以用于记录链路异常问题
     * */
    //CStatus status = pipeline->registerGElement<MyNode1>(&a, {}, "nodeA");    // 将名为nodeA，无执行依赖的node信息，注册入pipeline中
    //status += pipeline->registerGElement<MyNode2>(&b, {a}, "nodeB");    // 将名为nodeB，依赖a执行的node信息，注册入pipeline中
    //status += pipeline->registerGElement<MyNode1>(&c, {a}, "nodeC");
    //status += pipeline->registerGElement<MyNode2>(&d, {b, c}, "nodeD");    // 将名为nodeD，依赖{b,c}执行的node信息，注册入pipeline中

    CStatus status = pipeline->registerGElement<SimpleNodeA>(&a, {}, "node-1");
    status += pipeline->registerGElement<SimpleNodeB>(&b, {a}, "node-2-1");    // 将名为nodeB，依赖a执行的node信息，注册入pipeline中
    status += pipeline->registerGElement<SimpleNodeC>(&c, {a}, "node-2-2");
    status += pipeline->registerGElement<SimpleNodeD>(&d, {b, c}, "node-3");    // 将名为nodeD，依赖{b,c}执行的node信息，注册入pipeline中

    if (!status.isOK()) {
        return;    // 使用时，请对所有CGraph接口的返回值做判定。今后tutorial例子中省略该操作。
    }

    /**
    UThreadPoolConfig config;             // （可选）推荐根据自己设定的dag逻辑，来配置调度信息
    config.default_thread_size_ = 2;
    config.secondary_thread_size_ = 0;    // 更多配置信息，请参考 UThreadPoolDefine.h 中的描述
    pipeline->setUniqueThreadPoolConfig(config);
    */

    /* 图信息初始化，准备开始计算 */
    status += pipeline->init();

    /* 运行流图信息。初始化后，支持多次循环计算 */
    //for (int i = 0; i < 1; i++) {
        status += pipeline->run();
        //CGRAPH_ECHO("==== tutorial_simple, loop : [%d], and run status = [%d].", i + 1, status.getCode());
    //}

    CGRAPH_ECHO("==== tutorial_simple, run out.");
    //std::unique_lock<std::recursive_mutex> global_lock(s_node_mutex);
    /* 图信息逆初始化，准备结束计算 */
    status += pipeline->destroy();
    CGRAPH_ECHO("==== tutorial_simple, destroyed.");
    GPipelineFactory::remove(pipeline);
    CGRAPH_ECHO("==== tutorial_simple, pipeline removed.");
}

int main () {
    tutorial_simple();
    return 0;
}

下面是程序运行输出：
[2023-12-12 16:48:45.118] [node-1], enter SimpleNode-A run function. Sleep for 1 second ...
[2023-12-12 16:48:46.132] [node-2-2], enter SimpleNode-C run function. Sleep for 1 second ...
[2023-12-12 16:48:46.132] [node-2-1], enter SimpleNode-B run function. Sleep for 3 second ...
[2023-12-12 16:48:47.143] [node-2-2], leave SimpleNode-C
[2023-12-12 16:48:47.145] , errorCode = [-1], errorInfo = [error - C].
[2023-12-12 16:48:47.146] ==== tutorial_simple, run out.
[2023-12-12 16:48:49.142] [node-2-1], leave SimpleNode-B

下面是崩溃时的调用栈：
 	vcruntime140d.dll!00007ffa5c15f92c()	Unknown
 	T01-Simple.exe!std::_Char_traits<char,int>::move(char * const _First1, const char * const _First2, const unsigned __int64 _Count) Line 120	C++
 	T01-Simple.exe!std::string::assign(const char * const _Ptr, const unsigned __int64 _Count) Line 3378	C++
 	T01-Simple.exe!std::string::operator=(const std::string & _Right) Line 3190	C++
 	T01-Simple.exe!CGraph::internal::CSTATUS::operator=(const CGraph::internal::CSTATUS & status) Line 74	C++
>	T01-Simple.exe!CGraph::GDynamicEngine::process::__l2::<lambda>() Line 105	C++
 	[External Code]	
 	T01-Simple.exe!CGraph::UTask::TaskDerided<std::packaged_task<void __cdecl(void)>,std::packaged_task<void __cdecl(void)>>::call() Line 32	C++
 	T01-Simple.exe!CGraph::UTask::operator()() Line 45	C++
 	T01-Simple.exe!CGraph::UThreadBase::runTask(CGraph::UTask & task) Line 89	C++
 	T01-Simple.exe!CGraph::UThreadPrimary::processTask() Line 95	C++
 	T01-Simple.exe!CGraph::UThreadBase::loopProcess() Line 149	C++
 	T01-Simple.exe!CGraph::UThreadPrimary::run() Line 86	C++
 	[External Code]

**Comment by ChunelFeng** [comment]
您好，感谢您的反馈。

这是已知问题，请先试用 静态引擎来规避这个问题

```cpp
pipeline->setGEngineType(GEngineType::STATIC)
```

具体解决方案，我们会在今后实施和改进

**Comment by ChunelFeng** [comment]
感谢您的demo和test信息，这个问题应该是 windows和 mac/linux 系统的系统函数实现方式不一样的导致的。
我们在mac和 linux上做同样操作，不复现这个问题。

我们已经在最新版本中，在 windows平台下，尝试修复了这个问题，并且本地自测ok。欢迎升级最新版本自测体验。
再次感谢您的关注

**Comment by yaowenxin** [comment]
经测试，已经解决，多谢
