### ISSUE TITLE
线程池初始化vector竞争bug

### ISSUE THREAD

**Issue by DemoSeason** [ChunelFeng/CGraph#309]
Up你好，发现在UThreadPool.cpp(line54)调用初始时，进入到UThreadPrimary.run函数的any_of(line79)会引起pool_threads_竞争访问，导致异常，将UThreadPool.cpp的init修改如下可以，还请Up修改更新一下：
` 
CStatus UThreadPool::init() {
    CGRAPH_FUNCTION_BEGIN
    if (is_init_) {
        CGRAPH_FUNCTION_END
    }

    monitor_thread_ = std::move(std::thread(&UThreadPool::monitor, this));
    thread_record_map_.clear();
    primary_threads_.reserve(config_.default_thread_size_);
    for (int i = 0; i < config_.default_thread_size_; i++) {
        auto ptr = CGRAPH_SAFE_MALLOC_COBJECT(UThreadPrimary);    // 创建核心线程数
        ptr->setThreadPoolInfo(i, &task_queue_, &primary_threads_, &config_);
        //status += ptr->init();//todo modify

        // 记录线程和匹配id信息
        thread_record_map_[(CSize)std::hash<std::thread::id>{}(ptr->thread_.get_id())] = i;
        primary_threads_.emplace_back(ptr);
    }
    // 先初始化完成，再run
    for (const auto& th : primary_threads_) {
        status += th->init();
    }
    CGRAPH_FUNCTION_CHECK_STATUS

    /**
     * 策略更新：
     * 初始化的时候，也可以创建n个辅助线程。目的是为了配合仅使用 pool中 priority_queue 的场景
     * 一般情况下，建议为0。
     */
    status = createSecondaryThread(config_.secondary_thread_size_);
    CGRAPH_FUNCTION_CHECK_STATUS

    is_init_ = true;
    CGRAPH_FUNCTION_END
}`

**Comment by ChunelFeng** [comment]
您好，感谢您的关注，这一块的确是有点问题的。如果您对此有兴趣，欢迎给我们提供 pr信息。
如果没有意向的话，我们稍后也会自行修复这个问题。

也欢迎添加我个人微信，随时交流相关内容。再次感谢您的意见。

**Comment by ChunelFeng** [comment]
感谢您的意见，我日常开发基本在mac上进行，的确没遇到过类似情况，
但是review代码，的确按照您说的方式去 init是合理的。

我们已经在最新的版本中，更新了相关的内容。欢迎体验，和继续提供意见和建议。

**Comment by DemoSeason** [comment]
好的，我是在windows上开发的

**Comment by yaowenxin** [comment]
调试了一下午崩溃，最后发现是在这里。本想来提个bug，发现已经有这个issue了，早知道来搜一下就好了。

**Comment by ChunelFeng** [comment]
> 调试了一下午崩溃，最后发现是在这里。本想来提个bug，发现已经有这个issue了，早知道来搜一下就好了。

哈哈，新版本中已经修复了。欢迎尝试最新版本
