### ISSUE TITLE
[bug] 动态模式下执行，node中抛出异常，会导致卡死

### ISSUE THREAD

**Issue by ChunelFeng** [ChunelFeng/CGraph#31]

**Comment by ChunelFeng** [comment]
暂时可以通过直接 return CStatus("error info") 的方式避免此类问题出现

**Comment by yeshenyong** [comment]
请具体阐述

**Comment by yeshenyong** [comment]
您好，我是叶燊泳，已收到你的邮件。

**Comment by ChunelFeng** [comment]
可以考虑的 思路：
![image](https://user-images.githubusercontent.com/37905059/233086782-e4490ad9-c515-499e-b6c7-a6fbaee9cfcb.png)

**Comment by yeshenyong** [comment]
> 可以考虑的 思路： ![image](https://user-images.githubusercontent.com/37905059/233086782-e4490ad9-c515-499e-b6c7-a6fbaee9cfcb.png)

对于过于复杂的泛型应用，我保持悲观的的态度，但是你的需求提起日程了♥

**Comment by ChunelFeng** [comment]
已经想好一招了，就是直接在 oncrashed 方法中，将 expection 信息，转成 CStatus，然后返回回去。
我估计八成就没事了。   

只是觉得有点不符合意图了，就一直没试。

**Comment by ChunelFeng** [comment]
已经解决

**Comment by yeshenyong** [comment]
您好，我是叶燊泳，已收到你的邮件。
