### ISSUE TITLE
Message这块有没有例子

### ISSUE THREAD

**Issue by JackyLucifer** [ChunelFeng/CGraph#32]
有看到消息这块，能不能出个例子

类似执行某个事儿，在执行过程中外发消息，通过订阅消息，在解析消息内容的时候触发其他的执行

**Comment by ChunelFeng** [comment]
感谢关注。

https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T16-MessageSendRecv.cpp

可以参考一下这个，单进程内，多个pipeline之间的联动。T17也是类似的例子。

**Comment by JackyLucifer** [comment]
好的
