### ISSUE TITLE
Hope adding  vcpkg package for cgraph

### ISSUE THREAD

**Issue by QiuYilin** [ChunelFeng/CGraph#324]
I would like to suggest adding a  [vcpkg](https://github.com/microsoft/vcpkg) package for cgraph. This would make it easier for developers to use cgraph in their projects, especially those who are already using vcpkg to manage their dependencies.

**Comment by ChunelFeng** [comment]
你好，感谢您的意见。CGraph自身可以通过 xmake和 cmake编译，暂时不支持 bazel 和 vcpkg类似方式。

想确认一下，您是否有兴趣，pr 一下vcpkg 对应的内容？

**Comment by QiuYilin** [comment]
@ChunelFeng vcpkg的本质是git和cmake的 [组合使用](https://decovar.dev/blog/2022/10/30/cpp-dependencies-with-vcpkg/)，理论上越是标准的cmake包越是容易做成vcpkg的port。一些库虽然是cmake工程但是难以放到vcpkg主要原因是依赖太多，和vcpkg基线里的仓库有冲突，cgraph没有依赖应该没有这个问题。我最近才关注到到这个项目还没上手，后面我可能在自己fork的vcpkg registry里添加这个port方便个人使用，官方的vcpkg我不清楚怎么添加，原因是官方的规则规范我没完整地看完过。

**Comment by ChunelFeng** [comment]
好的，如果有使用需求，欢迎随时交流。也很期待您的意见和建议

**Comment by QiuYilin** [comment]
@ChunelFeng 我的[自定义注册表](https://github.com/QiuYilin/vcpkg-registry)中已经添加了cgraph的port，接下来我会看一下官方PR有什么要求，但是关于cmake配置文件我有个疑问，如果想让用户直接把CGraph源代码放到自己代码中编译,为什么不做成纯头文件的库，这样做的话用户不需要额外的dll依赖文件，同时工程依然可以作为外部target被找到。

**Comment by ChunelFeng** [comment]
主要是两个考量吧，
一个是 我们希望用户在写自己的 派生类，往上查看接口的时候，不需要看到具体的实现细节，或者接口更清晰一些。
还有就是全部使用 h文件，大概率会降低编译的速度。
