### ISSUE TITLE
提供一些好用的 debug功能

### ISSUE THREAD

**Issue by ChunelFeng** [ChunelFeng/CGraph#332]

**Comment by ceykmc** [comment]
请问有机制，可以让节点单步执行吗？
类似于调试的时候，在收到信号后，再执行下一个节点，执行完成后，继续等待后续节点执行的信号。

**Comment by ceykmc** [comment]
我是想调试整个pipeline的逻辑的。

**Comment by ceykmc** [comment]
刚发现和这个问题重复了。。。
https://github.com/ChunelFeng/CGraph/issues/45

**Comment by ChunelFeng** [comment]
新版本中，可以尝试通过 registerGNode 方法，注册一个节点，
并且在外部，人为将 GParam的值，修改为你需要的，然后直接运行 node的 run 方法，进行调试。

```cpp

  auto node = pipeline->registerGNode<MyWriteParamNode>();
  auto param = pipeline->getGParamWithNoEmpty<MyParam>("key");
  param->iCount = 10;    // 在这里，把参数修改为需要的值，而不需要修改 node内部的逻辑

  node->run();    // 运行 node的 run 方法

```

如果对项目感兴趣，欢迎添加我的个人微信（ChunelFeng），以便随时交流联系
