### ISSUE TITLE
进程间使用message部分

### ISSUE THREAD

**Issue by JackyLucifer** [ChunelFeng/CGraph#34]
进程间可以使用这个message部分么
类似
一个进程发message
一个进程收message

**Comment by ChunelFeng** [comment]
感谢关注。目前 CGraph 只支持单进程程序。

如果需要的话，可以自己在一个 node中，封装一个 socket或者消息队列的发送逻辑，
另外一个node中，封装对应的接收逻辑。即可实现跨进程的交互。

有关问题和使用场景，如果有需要交流的，可以通过微信联系
