### ISSUE TITLE
CGraph可以分析C项目，将其拆分成DAG图吗？

### ISSUE THREAD

**Issue by WWW233ZY1999** [ChunelFeng/CGraph#384]
我想把C项目（单文件或多文件）拆成有向无环图，任务图的节点是函数，但我现在只得到函数间的调用关系，无法得到具体的依赖关系与执行顺序。这个是我课题的一部分，得到图之后会设计调度算法。我现在没有拆图的依据，需要参考一下别人的工作。我在github上看到了你们团队的工作，不知道这个项目能提供我拆图的依据吗？

**Comment by ChunelFeng** [comment]
哦哦，色图本身是一个自定义的图构建工具，和编译本身没有太多关系
