### ISSUE TITLE
GMultiCondition的奇怪用法

### ISSUE THREAD

**Issue by ShawnXsw** [ChunelFeng/CGraph#385]
` GElementPtr b_multi_condition = pipeline->createGGroup<GMultiCondition<GMultiConditionType::SERIAL>>({pipeline->createGNode<MyNode1>(GNodeInfo("nodeB1"))}); `
`GElementPtr c_multi_condition = pipeline->createGGroup<GMultiCondition<GMultiConditionType::SERIAL>>({pipeline->createGNode<MyNode2>(GNodeInfo("nodeC1"))});`
`pipeline->registerGGroup(&b_multi_condition, {a}, "multiConditionB");`
`pipeline->registerGGroup(&c_multi_condition , {a}, "multiConditionC");`

请问如果我这样都只填入一个节来创建每个节点的话，是不是可以通过复写isMatch来控制各节点是否执行?

**Comment by ChunelFeng** [comment]
是的，您说的是没有问题。
但是，如果你在 b 和c 中的逻辑，不是很明确每次是否需要执行的话，
我们跟推荐使用 GMutable 来处理类似的问题

代码参考：https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T26-Mutable.cpp
视频参考：https://www.bilibili.com/video/BV1hb4y1M7Dn/?spm_id_from=333.788&vd_source=2c7baed805c6cb33d630d5d4546cf0be

**Comment by ShawnXsw** [comment]
SGTM
