### ISSUE TITLE
registerGElement 构造传参

### ISSUE THREAD

**Issue by LynnL4** [ChunelFeng/CGraph#390]
hello, 

createGNode 支持构造传参，
但是registerGElement不支持，请问这个是有什么限制吗，还是功能上没有实现，谢谢

**Comment by ChunelFeng** [comment]
我们提供了 两种通过 register 方法，构造模板 GNode 的方法，

请参考这个demo： https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T08-Template.cpp

如果有使用 registerGElement 传模板类的诉求，非常欢迎自己实现一个版本，然后pr过来

**Comment by LynnL4** [comment]
好的，我现在使用CreateNode后register的方式实现了相关需求，后续看是否可用直接register实现相关功能，谢谢。

**Comment by ChunelFeng** [comment]
如果对项目有兴趣，或者有使用需求，欢迎添加我的微信 ChunelFeng，方便随时交流。我们也很想了解大家的使用场景
