### ISSUE TITLE
对GPipeline::registerGElement接口中一些不恰当行为的困惑和建议

### ISSUE THREAD

**Issue by Void1024** [ChunelFeng/CGraph#4]
阅读了下源码，感觉`GPipeline::registerGElement`接口在处理外部创建node的情况下逻辑有些奇怪。
例如如下`case1`中，外部`new`的node存放于`hw`，但是会在`GPipeline::registerGElement`内部被修改，如果不事先备份一下的话，内存泄露就发生了。此时是否应该assert一下`*elementRef == nullptr`?
```
void case1() {
    GPipelinePtr pipeline = GPipelineFactory::create();
    GElementPtr hw = new HelloWorldNode();
    GElementPtr backup = hw;
    printf("%p\n", hw);
    printf("%p\n", backup);
    pipeline->registerGElement<HelloWorldNode>(&hw);    // 注册一个helloworld节点
    printf("%p\n", hw);
    printf("%p\n", backup);
    pipeline->process();    // 运行pipeline
    GPipelineFactory::destroy(pipeline);
    backup->run();
}
```
```
0x7fffc6dca4e0
0x7fffc6dca4e0
0x7fffc6dca9c0
0x7fffc6dca4e0
hello, world.
hello, world.
```
而在`case2`中，GPipeline的instance在析构时会delete所有记录下来的node指针，即使这个node是外部创建的(一般来讲生命周期应该由外部调用者来管控)，即使这个node不一定是`new`出来的。此时是否应该记录下node是否为internal对象，以确定要不要在析构的时候delete？
```
void case2() {
    GPipelinePtr pipeline = GPipelineFactory::create();
    GElementPtr hw = new HelloWorldNode();
    pipeline->registerGElement<HelloWorldNode>(&hw);    // 注册一个helloworld节点
    pipeline->process();    // 运行pipeline
    GPipelineFactory::destroy(pipeline);
    hw->run();
}
```
```
hello, world.
[1]    22131 segmentation fault (core dumped)  ./T00-HelloWorld
```

**Comment by ChunelFeng** [comment]
首先，感谢您的关注。关于您提到的两点，我讲一下我的看法哈。

case1中，`registerGElement()`函数中，如果外部注册的是GNode信息的话，是会在内部重新new一个GNode的，所以导致了您提到的backup指针不变，而hw指针被改变的情况。当然，如果没有后期的进一步处理，也会导致内存泄漏。

case2中，hw对应的二级指针地址，会在`GPipelineFactory::destroy(pipeline);`后被释放掉，是因为hw在`pipeline->registerGElement<HelloWorldNode>(&hw);`的时候，对应的二级指针已经被改动，并且被pipeline内部接管。

其实，目前CGraph中，还有一个很别扭的人为设定，就是在注册的时候，GNode的继承类外部必须传入为nullptr，才能顺利执行和释放。而GGroup的继承类（如GCluster，CRegion等）是需要在外部创建好之后（可以参考 T02-Cluster中的`pipeline->createGGroup<GCluster>`）才可以注册的，否则会返回错误码。

解决以上两个case的方案，可以是判断如果`pipeline->registerGElement<HelloWorldNode>(&hw)`的`*hw`不为空，则不做进一步处理，直接返回错误码。让外界知道，自己new的东东，没法注册进来，必须做到“谁申请，谁释放”。

还有一个我个人比较倾向的改进方案是：禁止GNode所有的子类在pipeline外部调用自己的 构造/析构函数，这样可以一劳永逸的解决外部资源分配不释放的问题，也更能体现框架的统一管理能力。但是因为其中涉及到了类的继承，并且实现GNode继承类的时候，大家其实习惯上更倾向不写构造函数，更不要说强限定写成private类型。所以，暂时也没啥好的思路。

如果这方面有什么经验或者建议的话，或者其他的解决方案的话，请随时指教。
我的微信是 ChunelFeng ，或者见readme中的二维码。希望能加到您的微信，以便随时请教。

**Comment by Void1024** [comment]
啊抱歉，我突然发现case2构造错了，其实应该类似下面这样
```
void case2() {
    GPipelinePtr pipeline = GPipelineFactory::create();
    GElementPtr hw = new HelloWorldNode();
    printf("%p\n", hw);
    using Dummy = GCluster;
    pipeline->registerGElement<Dummy>(&hw);    // 注册一个helloworld节点
    pipeline->process();    // 运行pipeline
    GPipelineFactory::destroy(pipeline);
    printf("%p\n", hw);
    hw->run();
}
```
```
0x7fffd06f44e0
hello, world.
0x7fffd06f44e0
[1]    24315 segmentation fault (core dumped)  ./T00-HelloWorld
```
当然case2里的这种写法本身是不太合理的，我只是想借此表达在不触发内部重新创建的情况下，外部创建的对象有可能会在pipeline析构时被尝试释放
这个问题导致真实使用中可能出现如下情况
```
void case3() {
    GPipelinePtr pipeline1 = GPipelineFactory::create();
    GPipelinePtr pipeline2 = GPipelineFactory::create();

    auto cluster = pipeline1->createGGroup<GCluster>({
         pipeline1->createGNode<HelloWorldNode>(GNodeInfo("nodeB1", 1))
    });
    printf("%p\n", cluster);
    cluster->run();
    pipeline2->registerGElement<GCluster>(&cluster);
    pipeline2->process();
    GPipelineFactory::destroy(pipeline2);
    printf("%p\n", cluster);
    cluster->run();
}
```
```
0x7fffc5d83c30
hello, world.
hello, world.
0x7fffc5d83c30
[1]    25024 segmentation fault (core dumped)  ./T00-HelloWorld
```
pipeline2在deinit时似乎错误的将cluster这个外部对象给释放了

**Comment by ChunelFeng** [comment]
您好，再次感谢关注。针对您提到的两个内容，我说一下我的看法。

首先，在最新的case2中的写法（申明注册GCluster，但实际上传入了GNode的new后实例）是不符合逻辑的。
这一点，后期程序中应该通过错误返回值提供出来。
当然，这也反应出来了 外部new 的内容，内部管控会出现问题的情况。

case3中，同时开辟两个pipeline，通过pipeline1来申请（并管理）cluster，然后将该cluster再注册到pipeline2中去执行。
pipeline2在被释放的时候，实际上也就把cluster析构了。从而也会影响到pipeline1的执行。
而且这样做，还有一个非常糟糕的后果：会影响参数传递的逻辑。

CGraph目前对这种两个（或多个）pipeline的支持，是基本为0的，下一步需要补齐。
暂时能想到以下几点：
1，明确GElement的归属和对应的pipeline，需要从逻辑上 确保 谁分配、谁管理、谁释放。
2，多个pipeline之间，param和element均不互通。但可以共享线程池资源。
3，还有一点就是，需要想办法禁止用户在外部直接new任何GElement（包括GNode和GGroup）内容，方便节点信息统一管理。

以下内容周末有空的时候，会尝试实现。大佬有什么其他的想法和意见，也请随时指教。

**Comment by christsun** [comment]
> 阅读了下源码，感觉`GPipeline::registerGElement`接口在处理外部创建node的情况下逻辑有些奇怪。
> 例如如下`case1`中，外部`new`的node存放于`hw`，但是会在`GPipeline::registerGElement`内部被修改，如果不事先备份一下的话，内存泄露就发生了。此时是否应该assert一下`*elementRef == nullptr`?
> 
> ```
> void case1() {
>     GPipelinePtr pipeline = GPipelineFactory::create();
>     GElementPtr hw = new HelloWorldNode();
>     GElementPtr backup = hw;
>     printf("%p\n", hw);
>     printf("%p\n", backup);
>     pipeline->registerGElement<HelloWorldNode>(&hw);    // 注册一个helloworld节点
>     printf("%p\n", hw);
>     printf("%p\n", backup);
>     pipeline->process();    // 运行pipeline
>     GPipelineFactory::destroy(pipeline);
>     backup->run();
> }
> ```
> 
> ```
> 0x7fffc6dca4e0
> 0x7fffc6dca4e0
> 0x7fffc6dca9c0
> 0x7fffc6dca4e0
> hello, world.
> hello, world.
> ```
> 
> 而在`case2`中，GPipeline的instance在析构时会delete所有记录下来的node指针，即使这个node是外部创建的(一般来讲生命周期应该由外部调用者来管控)，即使这个node不一定是`new`出来的。此时是否应该记录下node是否为internal对象，以确定要不要在析构的时候delete？
> 
> ```
> void case2() {
>     GPipelinePtr pipeline = GPipelineFactory::create();
>     GElementPtr hw = new HelloWorldNode();
>     pipeline->registerGElement<HelloWorldNode>(&hw);    // 注册一个helloworld节点
>     pipeline->process();    // 运行pipeline
>     GPipelineFactory::destroy(pipeline);
>     hw->run();
> }
> ```
> 
> ```
> hello, world.
> [1]    22131 segmentation fault (core dumped)  ./T00-HelloWorld
> ```

原来是你

**Comment by ChunelFeng** [comment]
@Void1024 大佬，我刚才更新了一版本 多个pipeline执行的功能，从代码层面禁止了group信息同时注册多个pipeline。
请大佬 再抽空review一下。

不过 对于外部new节点，自行管理生命周期的问题，暂时还是没有好的方法。

```cpp
GElementPtr a,b,c,d = nullptr;
```

主要问题卡点在：类似上述代码，看起来很平常，而且大家也经常会这样写。
但是实际的结果是：a和d 值为nullptr，但是 b和c实际上是非nullptr值，这种非空值传入CGraph中不好判定。

如果大佬有什么意见或者想法的话，请随时指教。感谢

**Comment by Void1024** [comment]
LGTM
另外，`GElementPtr a,b,c,d = nullptr`的行为只会将`d`初始化为`nullptr`，而a,b,c实际上是未初始化的，所以感觉上最好采用具有默认初始化语义的类型来管理，比如说`std::shared_ptr`或者自己封装一个类，而不是直接用裸指针

**Comment by ChunelFeng** [comment]
thx for ur msg
