### ISSUE TITLE
询问一下，跑一遍之后，外部怎么获取结果

### ISSUE THREAD

**Issue by JackyLucifer** [ChunelFeng/CGraph#40]
打个比方
有个过程是加法，需要输入参数a和b
gnode里面的功能是a+b的和
最后这个结果，在proceess之后
外部如何获取结果

**Comment by ChunelFeng** [comment]
最推荐的做法，是将你需要用 pipeline中值的部分，封装成node，即可在node中直接获取。

还可以通过 以下方式 获取。
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/37905059/218643775-c4d87678-8f23-4bbc-842e-f6f3e9d97c6a.png">

也可以用全局变量，但并不推荐。

**Comment by JackyLucifer** [comment]
大致明白整体结构用法了，谢谢回复
