### ISSUE TITLE
有考虑加入内存池之类的内存调度机制吗？

### ISSUE THREAD

**Issue by shi27feng** [ChunelFeng/CGraph#409]
如题

**Comment by ChunelFeng** [comment]
emmm ，是这样的，色图本身几乎不涉及任何 内存相关的操作。故，暂时没有引入内存池的需求和打算。
如果在实现node的过程中，需要用到内存池，可以考虑自行实现，或者使用类似 tc-malloc相关实现。

btw，之前的确有一点引入对象池的考虑，但由于 创建过程大都以模板的方式进行，所以也没有很强的诉求。
如果 对这一系列内容感兴趣的话，欢迎添加我的微信 ChunelFeng，随时交流联系
