### ISSUE TITLE
有关于动态addEParam

### ISSUE THREAD

**Issue by JackyLucifer** [ChunelFeng/CGraph#41]
在接收webscoket数据时，使用了提前创建好的pipeline

void revcData(std::string data)
{
   TestEPararm test;
   test.data = data;
   Element->addEparam(test)

   pipline->init();
   pipline->run();

}

大概是这样在接收数据的里面调用

发现这样调用我自己封装的EParam不会更新，只是反复调用而已

于是我把/GraphCtrl/GraphElement/GElement.inl

template<typename T,
        c_enable_if_t<std::is_base_of<GElementParam, T>::value, int> >
GElementPtr GElement::addEParam(const std::string& key, T* param) {
    //我把这行屏蔽了///CGRAPH_ASSERT_INIT_RETURN_NULL(false)
    CGRAPH_ASSERT_NOT_NULL_RETURN_NULL(param)
    if (local_params_.end() != local_params_.find(key)) {
        // 如果重复同名key信息，则删除原先的内容
        CGRAPH_DELETE_PTR(local_params_[key]);
    }
    T* cur = CGRAPH_SAFE_MALLOC_COBJECT(T);
    cur->clone(param);

    local_params_[key] = cur;    // 写入其中
    return this;
}

屏蔽了之后，反复调用参数内容是正常更新的

我想通过同一个pipeline，更新参数反复调用，有没有好的建议

我屏蔽的那个是不是就破坏了什么？

**Comment by ChunelFeng** [comment]
不推荐屏蔽。EParam设计出来的目的，是为了实现类似 GNode的可配置逻辑，并不是为了在运行时做值的替换。
故通过 CGRAPH_ASSERT_INIT_RETURN_NULL(false) 来限定了仅能在 init之前使用。
如果run 的时候设置，可能会出现一些 无法预期的并发问题（除非您自行控制）。

对于这种pipeline具体处理过程中，会用到的参数。推荐使用 GParam，在接受socket数据的时候，根据传入的信息赋值。
这个参数，可以被用到接下来的 pipeline流程中。

by the way，想了解一下您目前想落地的具体行业和领域，以便今后交流。

**Comment by JackyLucifer** [comment]
pipeline使用 addGAspect将动态的信息传入，完后再pipeline，init，run
是这样么
或者来个例子

搞机器人辅助程序的，要收发很多数据，为了提高执行效率使用这个库，方便并发处理事物

**Comment by ChunelFeng** [comment]
你好，感谢关注。这里有对应的例子：
https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T09-Aspect.cpp
https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T10-AspectParam.cpp

同文件夹下，还有很多相关例子。也可以参考 readme文件中的 推荐阅读中的文章。
比如：http://www.chunel.cn/archives/cgraph-aspect-introduce

**Comment by JackyLucifer** [comment]
好的，谢谢
