### ISSUE TITLE
请问这个场景是否适用

### ISSUE THREAD

**Issue by fool404** [ChunelFeng/CGraph#412]
批主

有A B C D E  F节点

A执行一次然后等待状B标志  执行B,      B执行完成后，等待C标志，执行【1-30】次C，执行完成后，再等待B标志， 这样循环5次之后， 再等待A标志，执行A节点 ，  A -B-C这样循环【1-10】次后执行F。

A、B、C当中任意一个执行过程中可能跳转到D中， 如果在D运行中，E执行标志为1时，执行E.

谢谢！

**Comment by ChunelFeng** [comment]
【A执行一次然后等待状B标志 执行B, B执行完成后，等待C标志，执行【1-30】次C，执行完成后，再等待B标志， 这样循环5次之后， 再等待A标志，执行A节点 ， A -B-C这样循环【1-10】次后执行F。】

类似等待的逻辑，可以考虑通过 GMessage 的逻辑实现。
循环本身，可以考虑通过 isHold 的 setLoop 两种方式实现。

如果 逻辑本身复杂，建议 先行画出来 一个流程图，然后尝试用色图构建，并且使用 dump 查看是否跟预想一致

【A、B、C当中任意一个执行过程中可能跳转到D中， 如果在D运行中，E执行标志为1时，执行E.】
这个逻辑，建议使用 GEvent实现。

**Comment by fool404** [comment]
批主，用Gmutable + ishold + daemon 是否可行

**Comment by ChunelFeng** [comment]
daemon 是由【时间】控制触发。在这种【次数】的场景下，应该不是很适合

**Comment by fool404** [comment]
好的 ，谢谢
