### ISSUE TITLE
node param读取写入的问题

### ISSUE THREAD

**Issue by Czhazha** [ChunelFeng/CGraph#414]
我是参照tutorial/MyGNode/MyWriteParamNode.h里面写的程序进行参数读写
关键代码是这么几句
`LOG(INFO) << "alarm_object_list size = " << sendInfoParam->pipelineinfo_list.front().alarm_information.alarm_object_list.size() << std::endl;  

pipelineinfo = sendInfoParam->pipelineinfo_list.front();  
LOG(INFO) << "pipelineinfo size = " << pipelineinfo.alarm_information.alarm_object_list.size() << std::endl;`
直接从sendInfoParam读取是如预期的size，但是pipelineinfo里面读取到的则一直是前序node未修改过的size.
我理解这里两个LOG应该打印一样的size，请问下是哪里可能有问题吗？
感谢

**Comment by ChunelFeng** [comment]
嗯，理论上，这两个方法，获取的是同一个 GParam对象的句柄。

有一点需要注意，是 GParam 对象中，有两个虚方法，分别在 pipeline->run(） 开始的瞬间，和结束的瞬间被执行。
如果你在 pipeline那一层读取参数的时候，可能会触发 以下两个方法。请查看一下 是否有对应的虚函数实现。

```cpp
protected:
    /**
     * 每次pipeline执行前，会调用一次setup，可以不实现
     * @return
     */
    virtual CStatus setup();

    /**
     * 每次pipeline执行结束，会调用一次reset
     * @param curStatus 本次pipeline执行的状态
     * @return
     * @notice 为丰富功能和简化操作，v2.4.0 版本中添加了curStatus作为入参，且取消纯虚函数设定。
     */
    virtual CVoid reset(const CStatus& curStatus);
```

btw，不是非常了解你表达的意思。可以的话，请贴上 简化后的源码

**Comment by Czhazha** [comment]
感谢回复。
我再定位定位吧，现在是在run内全部用CGRAPH_GET_GPARAM_WITH_NO_EMPTY获取的值进行参数的直接操作，目前看都还是正常的。
可能之前的异常是在获取到参数后，再从参数的一个list拷贝出来再处理导致的异常。因为想省一些结构嵌套。
setup和reset都没有设置过，异常是出现在一个node的run里面的。
