### ISSUE TITLE
有关线程池测试

### ISSUE THREAD

**Issue by SpencerChou** [ChunelFeng/CGraph#42]
不知道大佬有没有 关于线程池测试代码的实现可供借鉴，不太熟悉用了future什么的该怎么计算总耗时，以及多路并发往线程池投任务蛮好像也不太知道该怎么做

**Comment by ChunelFeng** [comment]
这个repo 可能会对你有所帮助：https://github.com/CodingHanYa/Hipe

**Comment by SpencerChou** [comment]
![image](https://user-images.githubusercontent.com/34341763/218985496-51d8c1d0-42e7-442f-8968-ea6cfd13f78b.png)
看了这位大佬的代码

但是里面对于timewait的实现，其中拿个pond.waitForTasks，等所有任务执行完，这个的实现大佬你的里面有类似接口嘛

如何判断所有任务执行完成呢

**Comment by SpencerChou** [comment]
![image](https://user-images.githubusercontent.com/34341763/219041249-68e2f31e-dbed-4a67-bde7-9845f8b6bc33.png)
wo'z我自己写了个这样的，不知道是否可取？

但是编译不过，仿照的大佬你的taskGroup submit的那个函数写的来着
![image](https://user-images.githubusercontent.com/34341763/219041378-354e6f06-83a6-45aa-8b74-f8bcb7c3e5e0.png)

**Comment by SpencerChou** [comment]
编译的问题解决了。。请教下 这样子轮询算时间是可行的不，我怕轮询太费时间，降低性能了

**Comment by ChunelFeng** [comment]
我想，轮询可能是会消耗一些性能。但是我暂时也想不到更好的方法。

但我总觉得，你那个 ttl的计算，可以放到循环的外面。或者测简单任务的时候，干脆不用。

那应该也是一个消耗的点。

**Comment by SpencerChou** [comment]
大佬，当时也是类似的思路测得性能得是嘛？ 我其实有一个好奇的点，也是另外那个repo提到的，扔几百万个空任务去线程池，这个测试和扔少量计算的cpu bound的任务有什么区别呢，为什么要做这种实验呢？它展现的性能优势，是因为什么带来的呢

**Comment by SpencerChou** [comment]
ttl的这个是因为 我不太熟c++de一些特性哈，future的使用，这个wait until不是必须有接收参数嘛？我才这么写的

**Comment by zd847239** [comment]
> ttl的这个是因为 我不太熟c++de一些特性哈，future的使用，这个wait until不是必须有接收参数嘛？我才这么写的

如果你想等待全部任务的完成，逐个 wait future 就行了。
```c++
for (auto& f : futures) f.wait();
```



> 大佬，当时也是类似的思路测得性能得是嘛？ 我其实有一个好奇的点，也是另外那个repo提到的，扔几百万个空任务去线程池，这个测试和扔少量计算的cpu bound的任务有什么区别呢，为什么要做这种实验呢？它展现的性能优势，是因为什么带来的呢

跑空任务是为了最大化框架开销。可以近似框架开销是 100%，空任务开销是 0%，这样 (总时间消耗/任务数量) 就是平均每个任务的框架开销。

**Comment by Codesire-Deng** [comment]
> ttl的这个是因为 我不太熟c++de一些特性哈，future的使用，这个wait until不是必须有接收参数嘛？我才这么写的

如果你想等待全部任务的完成，逐个 wait future 就行了。
```c++
for (auto& f : futures) f.wait();
```



> 大佬，当时也是类似的思路测得性能得是嘛？ 我其实有一个好奇的点，也是另外那个repo提到的，扔几百万个空任务去线程池，这个测试和扔少量计算的cpu bound的任务有什么区别呢，为什么要做这种实验呢？它展现的性能优势，是因为什么带来的呢

跑空任务是为了最大化框架开销。可以近似框架开销是 100%，空任务开销是 0%，这样 (总时间消耗/任务数量) 就是平均每个任务的框架开销。

**Comment by SpencerChou** [comment]
> 大佬，当时也是类似的思路测得性能得是嘛？ 我其实有一个好奇的点，也是另外那个repo提到的，扔几百万个空任务去线程池，这个测试和扔少量计算的cpu bound的任务有什么区别呢，为什么要做这种实验呢？它展现的性能优势，是因为什么带来的呢

有一个让我感到意外的地方，就是 虽然这样对比不对，我拿Java自带的fixed threadpool做测试，跑cpu bound的任务，毫无疑问c++线程池快，，，但是 我同样扔100w个空任务进去，Java的固定大小线程池居然只要192ms，而c++线程池要2s多。。。不知道有没有懂得大佬啊，怎么会这样

**Comment by Codesire-Deng** [comment]
> 我拿Java自带的fixed threadpool做测试，跑cpu bound的任务，毫无疑问c++线程池快，，，但是 我同样扔100w个空任务进去，Java的固定大小线程池居然只要192ms，而c++线程池要2s多。。。不知道有没有懂得大佬啊，怎么会这样

大概率 C++ 有某个地方弄错了。100W是很小的数字，超过一秒钟是很不正常的。如果能 show the code 那是最好的。

**Comment by SpencerChou** [comment]
https://github.com/CodingHanYa/Hipe
但是这个repo中，基准测试和其中dynamic得实现，确实100w也有好几秒呢，是因为动态创建线程导致得嘛

**Comment by SpencerChou** [comment]
```
void emptytest(UThreadPoolPtr tp, int task_num) {
    auto start = std::chrono::system_clock::now();
    std::vector<std::future<void>> futures;
    for (int i = 0; i < task_num; ++i) {

        futures.emplace_back(tp->commit([] {}));
    }
    int task_nums = futures.size();
    int cnt = 0;
    while (cnt < task_nums) {
        for (auto& fut : futures) {
            auto ttl = std::chrono::system_clock::now() ;
            const auto& futStatus = fut.wait_until(ttl);
            switch (futStatus) {
            case std::future_status::ready: cnt++;    // 正常情况，直接返回了
            default: continue;
            }
        }
    }
    auto end = std::chrono::system_clock::now();
    std::chrono::duration<double> elapsed_seconds = end - start;

    std::cout << "total: " << elapsed_seconds.count() << "s" << std::endl;
}
```

**Comment by SpencerChou** [comment]
我现在觉得是轮询所有任务结束太花时间了，for循环future，但是我不知道更好的办法，大佬有没有更好的解法啊

> > 我拿Java自带的fixed threadpool做测试，跑cpu bound的任务，毫无疑问c++线程池快，，，但是 我同样扔100w个空任务进去，Java的固定大小线程池居然只要192ms，而c++线程池要2s多。。。不知道有没有懂得大佬啊，怎么会这样
> 
> 大概率 C++ 有某个地方弄错了。100W是很小的数字，超过一秒钟是很不正常的。如果能 show the code 那是最好的。

**Comment by CodingHanYa** [comment]
@SpencerChou 线程池的快慢和你编写的方式有关，不同的性能往往是为了适应不同情景。动态线程池本身在空任务这方面就会比较慢。要对比空任务的话你可以跑一下上面提到的repo里面的稳定线程池和均衡线程池。我想以你机器的性能，跑出来的结果应该不至于比Java的差。记得控制变量。

**Comment by SpencerChou** [comment]
![image](https://user-images.githubusercontent.com/34341763/219313149-cb6356d0-1cda-4ce4-9f61-5c2d468299bd.png)

zhu'yao's主要是看到ChunelFeng大佬跑的对比试验也是空任务的。和固定线程池做对比，能有提升。。但是Java本身还包了个jvm我这机器没跑过，我觉得不应该

**Comment by SpencerChou** [comment]
> 

我发现我代码写错了，重复的future对象的ready状态进行了重复计算，所以实际上结束的要更早。。。那应该怎么轮询呢，求指教

**Comment by SpencerChou** [comment]
我发现我代码写错了，重复的future对象的ready状态进行了重复计算，所以实际上结束的要更早。。。那应该怎么轮询呢，求指教

我想的是用位运算的话，，但是假设是500w的任务，我怕位根本不够用啊

**Comment by CodingHanYa** [comment]
@SpencerChou 遍历一遍std::vector\<std::future\>，然后每一个调用.wait()，最后在这个遍历的前面和后面插入两个时间再在最后相减就可以了。你也可以看看我封装的timewait怎么实现的，很简单的。

**Comment by SpencerChou** [comment]
大佬好[CodingHanYa](https://github.com/CodingHanYa)[ChunelFeng](https://github.com/ChunelFeng)
迄今做了几组实验，发现动态扩缩容对线程池感觉基本上就没有性能提升啊
我用Chunel大佬的做了几组实验，发现core：8，max：16的 Cthread，和BS固定线程池的  8线程  和  16线程  做出来的实验结果，居然没什么区别。。。

我在此想求教二位的是，该如何设置实验，才能体现动态扩缩容线程池的优势呢？ 比如**实验场景？ 线程数？ 核心线程数？**
看似动态的有他的优势，可是我在实验中，一点也没体会到。。。。。

**Comment by SpencerChou** [comment]
@ChunelFeng @CodingHanYa 大佬好
迄今做了几组实验，发现动态扩缩容对线程池感觉基本上就没有性能提升啊
我用Chunel大佬的做了几组实验，发现core：8，max：16的 Cthread，和BS固定线程池的 8线程 和 16线程 做出来的实验结果，居然没什么区别。。。

我在此想求教二位的是，该如何设置实验，才能体现动态扩缩容线程池的优势呢？ 比如实验场景？ 线程数？ 核心线程数？
看似动态的有他的优势，可是我在实验中，一点也没体会到。。。。。

**Comment by ChunelFeng** [comment]
> @ChunelFeng @CodingHanYa 大佬好 迄今做了几组实验，发现动态扩缩容对线程池感觉基本上就没有性能提升啊 我用Chunel大佬的做了几组实验，发现core：8，max：16的 Cthread，和BS固定线程池的 8线程 和 16线程 做出来的实验结果，居然没什么区别。。。
> 
> 我在此想求教二位的是，该如何设置实验，才能体现动态扩缩容线程池的优势呢？ 比如实验场景？ 线程数？ 核心线程数？ 看似动态的有他的优势，可是我在实验中，一点也没体会到。。。。。

你好，感谢关注。平时白天需要上班，不太关注社区的事情。
今天晚上12点前，我会给出我之前用的测试用例。

关于类似的问题，我感觉需要结合实际使用场景的情景来考虑。
如果想要讨论，欢迎添加我微信，今后交流。

注意休息，少熬夜，嘿嘿。

**Comment by ChunelFeng** [comment]
```cpp
void demo() {
    auto ptr = new UThreadPool(true);
    int size = 4, times = 1000;    // 每轮执行4个并发，一共执行1000次。相当于跑了4000个空任务
    
    /*********计算这里的耗时情况******************************/
    for (int i = 0; i < times; i++) {
        UTaskGroup taskGroup;
        for (int j = 0; j < size; j++) {
            taskGroup.addTask([]{});    // 将任务放到一个taskGroup中，并发执行。执行的结果是无序的
        }
        ptr->submit(taskGroup);
    }
   /***************************************/
    delete ptr;
}

```

还有，就是没有任何证明表明，在任务数和资源固定的情况下，增减线程数量，会对效率有提升。
如果有影响，只会是反向的影响。

增减线程，主要是为了应对一些不固定的场景，比如，任务数量波动且资源充足的时候，有很好的效果

**Comment by SpencerChou** [comment]
> 增减线程，主要是为了应对一些不固定的场景，比如，任务数量波动且资源充足的时候，有很好的效果

对，我的意思就是这个，，，这种实验我不知道该咋做啊，我好想做一个这个实验出来。。
然后就是大佬你提到的很好的效果。。我感觉现在底层线程调度都很快啊。。感觉根本就测不出来效果啊，我也不知道该测哪些指标，怎么去定义要测的那个指标什么的，现在都想不出来，这个实验该咋做
