### ISSUE TITLE
机器视觉下的应用问题

### ISSUE THREAD

**Issue by Guyiguang** [ChunelFeng/CGraph#424]
批主，请教些概念性问题：

场景是机器视觉下的应用
1）动态图运行，静态图运行（以及微任务的定义）以及拓扑运行的区别以及应用场景能不能说明下；
2）在一个应用中同时存在实时运算（如图象处理）和耗时操作（如网络通信、磁盘读写、log读写、DB读写）等需求，建议的场景是多pipeline+多threadpool的场景来实施是吗？如果公用线程池会不会有被拖慢的风险。
3）关于调度的优化有哪些通用的步骤来评估瓶颈：工具，以及一些关键参数说明

多谢。

**Comment by ChunelFeng** [comment]
HI，你好，依次回答：

Q1:
动态运行，指的是在执行期间解图，如果没有特别诉求的话，就用这种默认的执行方式就好。
静态运行，是执行之前对dag进行分析和分块，然后按照分析的依赖关系进行执行。微任务指的是 执行耗时很短的任务，在这种模式下，会有一定的提升。
拓扑运行，就是将dag根据依赖关系，进行拓扑排序，然后串行执行。

Q2:
应用中，特别是视觉应用中，我理解调度耗时是原低于算法耗时，调度约为2-3us，算法约为20-30ms左右吧，不在一个数量级上。我理解，线程池和调度应该不会是瓶颈。
如果非常讲究的话，可以考虑将io较多的逻辑和图像算法，分到不同的pipeline中执行。并且设定不同的线程池。
或者是将 io任务，node->setBindingIndex(CGRAPH_LONG_TIME_TASK_STRATEGY) ，并且开辟几个 辅助线程，也可以稍有优化。
如果不想太care这些事情，我理解直接开几个线程好了

Q3:
这个我建议，自己根据自己的实际执行环境和目标，写简单测例来测试吧。
个人认为，只要有算法 or 磁盘交互逻辑的程序，调度层面基本都不会是性能卡点。
