### ISSUE TITLE
如何从当前node获取上一个node的输出？

### ISSUE THREAD

**Issue by jinfagang** [ChunelFeng/CGraph#43]
楼主如何从当前node获取上一个node的输出？

**Comment by ChunelFeng** [comment]
大佬您好，感谢您的关注。

CGraph自身设计，在获取参数的过程中，不关注依赖和非依赖逻辑。
主要的思路是，一处创建，任意位置获取。

有兴趣的话，可以参考一下这个demo：
https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T05-Param.cpp

和这篇文章：
http://www.chunel.cn/archives/cgraph-param-introduce

期待和欢迎大佬指教
