### ISSUE TITLE
定时器第一次执行的等待时间

### ISSUE THREAD

**Issue by ceykmc** [ChunelFeng/CGraph#431]
定时器类UTimer，在第一次执行时，需要先等待一个周期：
```
left_interval_ = interval;
origin_interval_ = interval;
```
如果周期interval设定的时间比较长，第一次执行等待的时间也比较长。
是不是立刻执行会比较好，left_interval_  初始赋值为0 ?

**Comment by ChunelFeng** [comment]
嗯嗯，个人理解哈，  
UTimer 对应的是 GDaemon 的逻辑，这个逻辑，本身是init（）的时候开始执行的，
如果是上来就执行，有一点担心，在 GDaemon中 无法获取 全局的 GParam，因为还没有初始化的时候构建。

当然了，如果有对此的强需求的话，建议自行改动一下

**Comment by ceykmc** [comment]
是给GDaemon模块用的，理解了。
我直接拿来当定时器工具用了。
