### ISSUE TITLE
请问 Aspect 在有isHold的节点 只执行1次吗？

### ISSUE THREAD

**Issue by fool404** [ChunelFeng/CGraph#432]
批主，好，
          如题，我想用aspect来中断pipeline,  但是现在发现aspect只执行了一次(isHold)，请问有什么办法可以中断pipeline运行吗？
谢谢！

**Comment by ChunelFeng** [comment]
你所描述的逻辑，实际上是在 如下文件的如下函数中控制的，

可以看到，对于 loop的逻辑，是会反复触发 切面执行；
但对 isHold() 而循环的逻辑，实际上是不会触发切面执行的。

如果一定要的话，建议在 run(） 方法中添加判断逻辑。
或者就是直接在 isHold()方法中， CGRPAH_THROW_EXCEPTION("stop") 类似的强杀的方式了。
需要 确保不出现 crash的话，在 最上层捕获异常即可

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/9b2fed38-3f66-4198-991e-3d4d1a8f3045">

**Comment by fool404** [comment]
好的 ，谢谢
