### ISSUE TITLE
两个独立的pipeline 使用send-rec 收发消息 的问题

### ISSUE THREAD

**Issue by fool404** [ChunelFeng/CGraph#439]
批主，好
           现在发现用例子里面的multipipeline 
           pubPipeLine->process(3)保持不变
           把subPipeline->process(3)改成 subPipeline->process(300)
           实际subPipeline还是执行三次， 请问是哪里设置不对吗？
           如果两个pipeline之间需要交互，还有其他方法推荐吗？

谢谢！

**Comment by ChunelFeng** [comment]
pub了三次，当然只能sub到3次啊。并没有哪里不合理啊

**Comment by fool404** [comment]
批主，我的理解是这样：两个pipeline是独立的， subPipeline不管有没有接收到消息，应该都按设定的次数执行完成，不应该受pubPipeline的次数影响, 不知道这样理解对不对。

**Comment by ChunelFeng** [comment]
是两个独立的ppln，没有任何关系。
但是，sub收不到信息，无法往下执行，是符合预期的正常现象吧。

**Comment by fool404** [comment]
好的，谢谢！
