### ISSUE TITLE
cluster 等能不能中途根据条件打断循环？

### ISSUE THREAD

**Issue by BADBOY-Aaron** [ChunelFeng/CGraph#442]
作者你好，如下图，考不考虑，让cluster等能够不用制定loop size，而是可以设置能loop后，自定义loop退出条件，终止loop后继续执行后面的流程，而不是直接退出整个流程
![cluster](https://github.com/user-attachments/assets/bbc1756a-17aa-4901-a3fa-b9bf075dea29)

**Comment by ChunelFeng** [comment]
两个方案，如果是想执行 n次cluster中的逻辑（n值不确定，需要根据运行时的情况来判断）， 然后继续执行后面的逻辑，则建议复写 cluster 的 isHold()方法，
参考：https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T14-Hold.cpp

如果是执行到 b1->b2->b3 的中间，想停止执行 当前group，又不想退出 pipeline 的话， GCluster 的功能就不合适了。

两个思路，建议参考：
GMultiCondition: https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T21-MultiCondition.cpp

或者

GMutable(推荐): https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T26-Mutable.cpp
