### ISSUE TITLE
cluster嵌套循环 条件中断当前循环

### ISSUE THREAD

**Issue by fool404** [ChunelFeng/CGraph#461]
批主好

         Group A中嵌套Group B \ C \ D,             
B中有B1\B2\B3
C中有C1\C2\C3
D中有D1\D2\D3

A循环6次， 如果现在要在B\C\D中任一个节点中中断A当前循环(1)，执行下一个循环(2)，请指导一下用什么方式比较合理，谢谢？

**Comment by ChunelFeng** [comment]
是这样的， b,c,d 均属于 a 中的内容，目前色图的机制中，是没有不同层之间（比如A和B) 或者不同 group之间（B和C）相互作用的逻辑的。

其实，甚至 不同任意不同 node 之间（比如 B1 和 B2）都没有，都是通过 group 的逻辑来控制的。

如果需要您说的上述逻辑，我理解可以是 B1B2....D2D3 均继承一个 BasicGNode，BasicGNode 中实现了 isMatch() 的逻辑，来控制 本node是否执行。

然后 B（b1b2b3），C，D 是一个串行的 GMultiCondition 的组，通过 GParam 来控制这个node是否运行的逻辑。
比如 计算到 C2了，发现需要继续做A的循环了，就控制 C3D1D2D3 的 isMatch 为 false 即可。

**Comment by fool404** [comment]
谢谢解答， 现在遇到一个问题， 就是在B中已经将C和D的isMatch的条件改成false了(c1，c2,c3 也加了isMatch)， 但是在C和D仍然执行了， isMatch使用需要注意一些什么啊

**Comment by ChunelFeng** [comment]
使用问题，已经解决
