### ISSUE TITLE
GEngine.h编译上的小问题

### ISSUE THREAD

**Issue by starfisher** [ChunelFeng/CGraph#464]
<img width="1711" alt="image" src="https://github.com/user-attachments/assets/bce7f666-3058-425c-8bb6-7e52cde325d4" />
CGraph/GraphCtrl/GraphElement/_GEngine/GEngine.h:66:19: error: use of overloaded operator '==' is ambiguous (with operand types 'int' and 'std::atomic<CSize>' (aka 'atomic<unsigned long>'))

**Comment by ChunelFeng** [comment]
你好，仅在编译动态库的时候报错，看上去应该是编译器问题。
我们会在接下来的版本中，对这一块进行改进。确保 动态库也能正常编译和引入。感谢
