### ISSUE TITLE
run 运行错误返回问题

### ISSUE THREAD

**Issue by starfisher** [ChunelFeng/CGraph#465]
run方法只要有一次返回的是错误，后续执行的结果就一直是运行失败了，demo如下，通过给MyNode1添加一个成员变量count，count每次执行累加，首次为0执行返回err，后续执行不应该继续是err的。

#include "CGraph/CGraph.h"

using namespace CGraph;

class MyNode1 : public CGraph::GNode {
public:
    CStatus run() override {
        CGRAPH_SLEEP_SECOND(1)
        if(count == 0) {
            CGraph::CGRAPH_ECHO("[%s], enter MyNode1 run function. Sleep for 1 second ... ", this->getName().c_str());
            CGraph::CGRAPH_ECHO("++++++++++++++count = [%d]", count++);
            return CStatus(-1, "err");
        }
        CGraph::CGRAPH_ECHO("-------------count = [%d]", count++);
        CStatus status;
        return status;
    }
    CStatus destroy() override {
        CStatus status;
        CGraph::CGRAPH_ECHO("[%s], enter MyNode1 destroy function. Sleep for 1 second ... ", this->getName().c_str());
        CGRAPH_SLEEP_SECOND(1)
        return status;
    }
private:
    int count = 0;
};

class MyNode2 : public CGraph::GNode {
public:
    // 执行过程中，init 和 destroy 方法，单次执行，可选择性实现
    // run 方法可以多次执行，且必须实现
    CStatus init() override {
        CStatus status;
        CGraph::CGRAPH_ECHO("[INIT] [%s], enter MyNode2 init function.", this->getName().c_str());
        return status;
    }
    CStatus run() override {
        CStatus status;
        CGraph::CGRAPH_ECHO("[%s], enter MyNode2 run function. Sleep for 2 second ... ", this->getName().c_str());
        CGRAPH_SLEEP_SECOND(2)
        return status;
    }
    CStatus destroy() override {
        CStatus status;
        CGraph::CGRAPH_ECHO("[DESTROY] [%s], enter MyNode2 destroy function.", this->getName().c_str());
        return status;
    }
};

void tutorial_simple() {
    GPipelinePtr pipeline = GPipelineFactory::create();
    GElementPtr a, b, c, d = nullptr;
    CStatus status = pipeline->registerGElement<MyNode1>(&a, {}, "nodeA");    // 将名为nodeA，无执行依赖的node信息，注册入pipeline中
    status += pipeline->registerGElement<MyNode2>(&b, {a}, "nodeB");    // 将名为nodeB，依赖a执行的node信息，注册入pipeline中
    if (!status.isOK()) {
        return;    // 使用时，请对所有CGraph接口的返回值做判定。今后tutorial例子中省略该操作。
    }
    status += pipeline->init();
    for (int i = 0; i < 3; i++) {
        status += pipeline->run();
        CGRAPH_ECHO("==== tutorial_simple, loop : [%d], and run status = [%d].", i + 1, status.getCode());
    }
    status += pipeline->destroy();
    GPipelineFactory::remove(pipeline);
}

int main(int argc, char** argv) {
    tutorial_simple();
}

**Comment by ChunelFeng** [comment]
问题出现在这个循环过程中的 += 信息。 如果你改成 =，就符合预期了。
+= 的意思是，在有错误的情况下，保留错误信息。
= 的意思是，直接赋值

```cpp
for (int i = 0; i < 3; i++) {
  status += pipeline->run();
  CGRAPH_ECHO("==== tutorial_simple, loop : [%d], and run status = [%d].", i + 1, status.getCode());
}

```

有兴趣的话，欢迎提供一下 pr 信息

**Comment by starfisher** [comment]
感谢，这个地方确实没注意到
