### ISSUE TITLE
关于node节点的beforeRun()和afterRun()

### ISSUE THREAD

**Issue by libaineu2004** [ChunelFeng/CGraph#51]
先看源代码
1、main.cpp源码如下：
void test_opencv()
{
    GPipelinePtr pipeline = GPipelineFactory::create();
    CStatus status;
    GElementPtr a = nullptr;
    GElementPtr b = nullptr;

    status += pipeline->registerGElement<CNodeReadImage>(&a, {}, "readNodeA");
    // status += pipeline->registerGElement<CNodeReadImage>(&b, {a}, "readNodeB");

    if (!status.isOK())
    {
        return;
    }

    status += pipeline->init();
    status += pipeline->run();
    status += pipeline->destroy();
    GPipelineFactory::remove(pipeline);
}

int main(int argc, char *argv[])
{
    test_opencv();
    return 0;
}

2、nodereadimage.cpp源文件如下
CStatus CNodeReadImage::init()
{
    CGraph::CGRAPH_ECHO("[%s], enter init function", this->getName().c_str());
    return CStatus();
}

CStatus CNodeReadImage::run()
{
    CStatus status;
    CGraph::CGRAPH_ECHO("[%s], enter run function", this->getName().c_str());
    // CGRAPH_SLEEP_SECOND(1)
    return status;
}

CStatus CNodeReadImage::destroy()
{
    CGraph::CGRAPH_ECHO("[%s], enter destroy function", this->getName().c_str());
    return CStatus();
}

CStatus CNodeReadImage::beforeRun()
{
    CGraph::CGRAPH_ECHO("[%s], enter beforeRun function", this->getName().c_str());
    return CStatus();
}

CStatus CNodeReadImage::afterRun()
{
    CGraph::CGRAPH_ECHO("[%s], enter afterRun function", this->getName().c_str());
    return CStatus();
}

再看编译之后的运行结果：
[CGraph] [Mon Feb 20 19:06:06 2023] [readNodeA], enter beforeRun function
[CGraph] [Mon Feb 20 19:06:06 2023] [readNodeA], enter afterRun function
[CGraph] [Mon Feb 20 19:06:06 2023] [readNodeA], enter init function
[CGraph] [Mon Feb 20 19:06:06 2023] [readNodeA], enter beforeRun function
[CGraph] [Mon Feb 20 19:06:06 2023] [readNodeA], enter run function
[CGraph] [Mon Feb 20 19:06:06 2023] [readNodeA], enter afterRun function
[CGraph] [Mon Feb 20 19:06:06 2023] ..\cvGraphDemo\graph\GraphCtrl\GraphPipeline\GPipeline.cpp | CGraph::GPipeline::run | line = [75], errorCode = [-1], errorInfo = [pipeline done status check failed...].
[CGraph] [Mon Feb 20 19:06:06 2023] [readNodeA], enter destroy function

我的疑问如下：
1、node节点在init之前，怎么先执行了beforeRun和afterRun？
2、为什么会报错？errorCode = [-1], errorInfo = [pipeline done status check failed...]
哪里有问题？

**Comment by ChunelFeng** [comment]
你好，感谢关注。

先回答第二个问题，node中的 beforeRun 和 afterRun 是内部解图的固定逻辑，
继承并改写这两个方法之后，导致了内部解图逻辑混乱。
之所以这两个函数，是virtual函数，是因为GCluster中，有复写这块逻辑的内容。
如果想设特定函数，在 run()方法前执行，可以考虑添加切面逻辑。

第一个问题，在init()之前执行，是因为在初始化的时候，
通过类似的解图逻辑，来确认pipeline是否是一个 可执行的dag

**Comment by libaineu2004** [comment]
继承并改写这两个方法之后，导致了内部解图逻辑混乱???
那就是说，不能去继承和改写它们了？

**Comment by ChunelFeng** [comment]
是的， 针对 GNode，可以复写的接口 包括：
init()
run()
destroy()
isHold()    // 是否继续执行
crashed()

其他均不可复写
