### ISSUE TITLE
能否把CGraph封装成动态库或静态库的方式，方便用户植入自己的程序？

### ISSUE THREAD

**Issue by libaineu2004** [ChunelFeng/CGraph#52]
能否在现有的基础上，新增宏定义，可以控制CGraph为源码/动态库/静态库的三种方式供用户使用？
在实际使用中，以库的方式植入自己的程序比较方便使用。

**Comment by ChunelFeng** [comment]
您好，关于 编译静/动态库的操作，在 [cmakelists.txt](https://github.com/ChunelFeng/CGraph/blob/main/CMakeLists.txt)  文件中，已经有所体现。
<img width="603" alt="image" src="https://user-images.githubusercontent.com/37905059/220356137-1da1841b-79e5-43c0-a695-821e757ad498.png">

至于提供库文件，个人比较推荐的 方式是，所有工程依赖 CGraph的功能。
如果说，只是个别部分用到dag调度功能，可以写一个完整功能的 pipeline，
然后封装成c函数（如 my_func），然后封装成 库文件，供外人调用

```cpp
void my_func() {
    // create pipeline
    // init, run, destroy...
}
```

**Comment by libaineu2004** [comment]
add_library(CGraph SHARED ${CGRAPH_SRC_LIST})    # 编译libCGraph动态库
这样编译只生成了CGraph.dll文件，但是没有生成导入库文件CGraph.lib
我是希望提供include头文件/CGraph.dll/CGraph.lib这三类文件作为接口调用。

**Comment by ChunelFeng** [comment]
您好，针对 __declspec(dllexport) 类似windows 特定逻辑，暂不支持。
如果是强需要，请自行修改。我们可以配合提供修改思路。

刚才在最新版本 v2.3.4中，优化了windows中的线程池调度逻辑，欢迎体验。

还有一点，新版本中，修改了 GParam的 reset() 接口，
如果使用新版本的话，请实现 GParam的  `CVoid reset(const CStatus& curStatus) override` 接口。

curStatus 是本次pipeline执行的结果状态，可用可不用。

**Comment by libaineu2004** [comment]
> 

希望后续版本中，能使用宏定义来新增针对 __declspec(dllexport) 类似windows 特定逻辑

**Comment by ChunelFeng** [comment]
您好，在新版本中，体验 graphviz功能接口：

![image](https://user-images.githubusercontent.com/37905059/220937341-7b9fba7d-b358-4120-aa86-ebccacaf4e5d.png)

```cpp

void demo() {
    GPipelinePtr pipeline = GPipelineFactory::create();
    GElementPtr a, b= nullptr;

    CStatus status = pipeline->registerGElement<MyNode1>(&a, {}, "nodeA");
    status += pipeline->registerGElement<MyNode2>(&b, {a}, "nodeB");
    pipeline->dump();

    GPipelineFactory::remove(pipeline);
}

```

查看graphviz，请参考接口.h文件

**Comment by libaineu2004** [comment]
![image](https://user-images.githubusercontent.com/11898277/221080436-84e73ec4-9c0c-47d8-b8cf-df9ad870ec42.png)
不错的功能，非常棒
http://www.graphviz.org/
https://dreampuf.github.io/GraphvizOnline/
