### ISSUE TITLE
请问可视化pipeline->dump()生成了文本后如何实现逆解？

### ISSUE THREAD

**Issue by libaineu2004** [ChunelFeng/CGraph#57]
如题，我们通过pipeline->dump()可以得到可视化需要的文本字符串。
https://dreampuf.github.io/GraphvizOnline/
例如，
digraph CGraph {
compound=true;
p000001E8A5B24CD0[label="nodeA"];
p000001E8A5B24CD0 -> p000001E8A5B28FD0;
p000001E8A5B24CD0 -> p000001E8A5B2A180;
p000001E8A5B28FD0[label="nodeB"];
p000001E8A5B28FD0 -> p000001E8A5B2A320;
p000001E8A5B2A180[label="nodeC"];
p000001E8A5B2A180 -> p000001E8A5B2A320;
p000001E8A5B2A320[label="nodeD"];
}
或者
digraph G {
  start -> a0;
  start -> b0;
  a1 -> b3;
  b2 -> a3;
  a3 -> a0;
  a3 -> end;
  b3 -> end;
}

现在我的项目需求是，如何通过这个字符串来实现逆解？
所谓的逆解指的是：
1、先把digraph CGraph {...}这字符串本地持久化，保存为demo.txt文件
2、我的应用程序打开demo.txt文件，解析它，然后生成相应的数据结构
3、解析之后，根据得到的数据结构，来动态生成该图对应的Pipeline或者MultiPipeline
4、运行Pipeline或者MultiPipeline

请问如何实现这个逆解？有无例程？

**Comment by ChunelFeng** [comment]
你好，个人认为，如果想实现逆向解析的话，用 graphviz格式可能不是很好。

自行设定 json 格式，可读性会更好，也应该会更容易实现一点。供参考

**Comment by libaineu2004** [comment]
> 你好，个人认为，如果想实现逆向解析的话，用 graphviz格式可能不是很好。
> 
> 自行设定 json 格式，可读性会更好，也应该会更容易实现一点。供参考

格式还好，可以采用xml或者json格式，都行。
问题是怎么来动态生成该图对应的Pipeline或者MultiPipeline？
这个有没例程可以参考？

**Comment by ChunelFeng** [comment]
暂无例子， 色图当前未引入三方库，无法实现 json解析和读取的逻辑

如果顺利的话，预计等支持 python语言之后，会提供类似的demo

最近开发者内部讨论的主要内容，都是围绕如何兼容python来展开的

**Comment by libaineu2004** [comment]
> 暂无例子， 色图当前未引入三方库，无法实现 json解析和读取的逻辑
> 
> 如果顺利的话，预计等支持 python语言之后，会提供类似的demo
> 
> 最近开发者内部讨论的主要内容，都是围绕如何兼容python来展开的

那请你给点思路吧，xml或json解析的功能我自己可以实现。
但是怎么动态生成Pipeline或者MultiPipeline？怎么注册这些解析出来的节点？pipeline->registerGElement？？

**Comment by ChunelFeng** [comment]
暂无明确思路，请自行思考

**Comment by ChunelFeng** [comment]
您好，不是很明确您的需求和想法。
是否可以新开一个 issue ，详细描述情况？
