### ISSUE TITLE
region和cluster的超多层嵌套下，执行会卡住

### ISSUE THREAD

**Issue by woodx9** [ChunelFeng/CGraph#58]
嵌套等于5层，有几率卡住，超过五层必卡住
[T20-Test.txt](https://github.com/ChunelFeng/CGraph/files/10833164/T20-Test.txt)

**Comment by woodx9** [comment]
可以通过加大CGraph里的线程池 主线程数量来解决问题，不过可能带来性能问题

**Comment by ChunelFeng** [comment]
已知问题，正常group之间的嵌套无异常。
卡住的主要原因，是层数太深，任务太多，导致线程池中资源被耗尽。

暂时列入 非正常使用场景中吧。待架构升级，或者有新调度思路的时候，统一解决
