### ISSUE TITLE
把pipeline定义为全局变量，destroy函数不能注销节点吗？

### ISSUE THREAD

**Issue by libaineu2004** [ChunelFeng/CGraph#68]
我的应用场景是把pipeline定义为全局变量，ui主界面每次点击【运行测试】按钮，每次都重新注册节点，然后运行。
源码如下：
#include "MyGNode/MyNode1.h"
#include "MyGNode/MyNode2.h"

using namespace CGraph;

GPipelinePtr pipeline = nullptr;

void init()
{
    pipeline = GPipelineFactory::create();
}

void uninit()
{
    GPipelineFactory::remove(pipeline);
}

void test()
{
    GElementPtr a, b = nullptr;
    CStatus status = pipeline->registerGElement<MyNode1>(&a, {}, "nodeA");
    status += pipeline->registerGElement<MyNode2>(&b, {a}, "nodeB");
    if (!status.isOK())
    {
        return;
    }

#if 1
    status += pipeline->init();
    status += pipeline->run();
    status += pipeline->destroy();
#else
    status += pipeline->process(); //process函数，相当于init(),run()*n,destroy()函数，同时调用
#endif
}

int main()
{
    init();
    test();//运行测试1
    test();//运行测试2
    test();//运行测试3
    uninit();
    return 0;
}

来看打印输出的结果是：
[CGraph] [Sun Mar  5 22:08:35 2023] [nodeB], enter MyNode2 init function.
[CGraph] [Sun Mar  5 22:08:35 2023] [nodeA], enter MyNode1 run function. Sleep for 1 second ...
[CGraph] [Sun Mar  5 22:08:36 2023] [nodeB], enter MyNode2 run function. Sleep for 2 second ...
[CGraph] [Sun Mar  5 22:08:38 2023] [nodeB], enter MyNode2 destroy function.
[CGraph] [Sun Mar  5 22:08:38 2023] [nodeB], enter MyNode2 init function.
[CGraph] [Sun Mar  5 22:08:38 2023] [nodeB], enter MyNode2 init function.
[CGraph] [Sun Mar  5 22:08:38 2023] [nodeA], enter MyNode1 run function. Sleep for 1 second ...
[CGraph] [Sun Mar  5 22:08:39 2023] [nodeB], enter MyNode2 run function. Sleep for 2 second ...
[CGraph] [Sun Mar  5 22:08:41 2023] [nodeB], enter MyNode2 destroy function.
[CGraph] [Sun Mar  5 22:08:41 2023] [nodeB], enter MyNode2 destroy function.
[CGraph] [Sun Mar  5 22:08:41 2023] [nodeB], enter MyNode2 init function.
[CGraph] [Sun Mar  5 22:08:41 2023] [nodeB], enter MyNode2 init function.
[CGraph] [Sun Mar  5 22:08:41 2023] [nodeB], enter MyNode2 init function.
[CGraph] [Sun Mar  5 22:08:41 2023] [nodeA], enter MyNode1 run function. Sleep for 1 second ...
[CGraph] [Sun Mar  5 22:08:42 2023] [nodeB], enter MyNode2 run function. Sleep for 2 second ...
[CGraph] [Sun Mar  5 22:08:44 2023] [nodeB], enter MyNode2 destroy function.
[CGraph] [Sun Mar  5 22:08:44 2023] [nodeB], enter MyNode2 destroy function.
[CGraph] [Sun Mar  5 22:08:44 2023] [nodeB], enter MyNode2 destroy function.

看调试日志，每执行一次test()，init function和destroy function就会增多一次。
感觉不妙，pipeline->destroy()是不是没有把注册的节点自动删除掉？

**Comment by ChunelFeng** [comment]
使用错误，请参考说明文档或源码。
项目更多用于技术交流，暂不考虑支持商用项目，技术选型时请谨慎。
