### ISSUE TITLE
怎么给整个图传入初始的数据？

### ISSUE THREAD

**Issue by jinfagang** [ChunelFeng/CGraph#70]
我有一个SourceNode，它的工作就是读取视频流。

但是我如果在这个Node的init方法里面去打开video文件或者摄像头，每次我都得改init，有没有什么办法，把参数在整个程序的运行入口传进去？

这样我可以在args来进行参数传入。

**Comment by jinfagang** [comment]
或者有没有办法，在 `pipline.run()` 的时候，我每次run 都给他传入一个新的输入？

```

  status += pipeline->init();

  for (int i = 0; i < 3; i++) {
    status += pipeline->run();
    std::cout << "========> [burn] loop : " << i + 1
              << ", and run status = " << status.getCode() << std::endl;
  }

  status += pipeline->destroy();
  GPipelineFactory::remove(pipeline);
```


例如每次我在循环里面读取一个 新的 cv::Mat ，然后再run的时候传去？

**Comment by ChunelFeng** [comment]
你好，针对你提到的问题，在 pipeline类，也可以调用 getGParam<T>(key) 的接口。

这样的话，可以获得在run 之前或者pipeline的参数，并且作用于pipeline 中去。

或者 干脆在前面多加一个 获取流数据的node，专门做这一件事情也好

**Comment by jinfagang** [comment]
谢谢色哥
