### ISSUE TITLE
可以考虑换成 virtual 的函数类型

### ISSUE THREAD

**Issue by ChunelFeng** [ChunelFeng/CGraph#79]
https://github.com/ChunelFeng/CGraph/blob/fa73cfe30878ba872665ce2559531a1d33169b02/src/GraphCtrl/GraphElement/GElement.h#L225

**Comment by yeshenyong** [comment]
目前dump 逻辑最简化进行打印，若后续不同Element 有不同dumpEdge 逻辑，再考虑换
