### ISSUE TITLE
vs2015无法编译通过。

### ISSUE THREAD

**Issue by GFFFer** [ChunelFeng/CGraph#8]
看了介绍感觉设计得挺好的，想用用看，但是vs2015环境编译不通过，感觉了版本低了？

**Comment by ChunelFeng** [comment]
> 看了介绍感觉设计得挺好的，想用用看，但是vs2015环境编译不通过，感觉了版本低了？

你好，感谢关注。

vs2015环境我这边的确没有，也暂时不确定vs2015对C++17的支持是否完备。

我自己开发一般在MacOs上，ide是CLion。windows和linux也都通过CLion尝试编译和执行过。

vs2015的确没有试过，不过因为没有任何第三方引入，应该问题不大。

如果无法直接编译通过，可以贴出来编译未通过的位置，一起看看原因。

如果有任何问题，请添加我个人微信（ ChunelFeng ），当面交流应该能更快的定位和解决一些问题。

**Comment by GFFFer** [comment]
应该是不支持C++17，这个能否降低下C++版本，C++11 2015是完整支持的，感谢，因为其他类库原因没法升级vs环境。
![image](https://user-images.githubusercontent.com/58319894/149046043-9fe799df-6b3a-487d-b80c-fd6b439daacc.png)
![image](https://user-images.githubusercontent.com/58319894/149046097-70a5b539-754a-410a-ae60-a035907ff662.png)

**Comment by ChunelFeng** [comment]
我看了一下标红的地方，并不是语言版本的问题，更像是引入工程内部头文件依赖的问题

cpp17的功能，这里用的应该不多的。大都是cpp14版本。


方便的话，希望可以加我微信，一起远程定位和排查看看。

**Comment by ChunelFeng** [comment]
弱弱的问一下，老哥，怎么样了，有进展了么

**Comment by ChunelFeng** [comment]
通过降低C++版本和优化visual studio兼容性解决。

感谢老铁配合验证，希望今后多多指教和交流。

Mark一下，如有遇到类似问题的朋友，请联系我们

**Comment by kinggreat24** [comment]
> 通过降低C++版本至C++14，和 优化适配windows上 visual studio 2015版本 解决。
> 
> 感谢老铁配合验证，希望今后多多指教和交流。
> 
> Mark一下，如有遇到类似问题的朋友，请联系我们

您好，我也是Vs2015上面编译不过，请问您具体是怎么解决这个问题啊

**Comment by ChunelFeng** [comment]
> > 通过降低C++版本至C++14，和 优化适配windows上 visual studio 2015版本 解决。
> > 感谢老铁配合验证，希望今后多多指教和交流。
> > Mark一下，如有遇到类似问题的朋友，请联系我们
> 
> 您好，我也是Vs2015上面编译不过，请问您具体是怎么解决这个问题啊

您好，最新版本的master上，已经提供cpp14版本的适配。

将CMakeList.txt文件中的 
```cpp
# CGraph推荐使用C++17或以上版本。支持无缝切换C++14版本，仅有个别功能功能的弱化和剪裁。暂不支持C++11或以下版本
set(CMAKE_CXX_STANDARD 17)
```

修改为 set(CMAKE_CXX_STANDARD 14)，即可

**Comment by kinggreat24** [comment]
![image](https://user-images.githubusercontent.com/30688557/183576415-0a301798-df2e-4e32-a2b7-3a38ffef2131.png)
![image](https://user-images.githubusercontent.com/30688557/183576521-5721ab9e-55c4-4517-90d4-4d463a01f803.png)

我按照您说的，还是有一点问题，这个您之前遇到过吗

**Comment by ChunelFeng** [comment]
Hi，已经做对应优化。直接修改 一处CMakeLists.txt中信息，即可编译通过。

<img width="829" alt="image" src="https://user-images.githubusercontent.com/37905059/186062736-d1fc731e-b092-4a59-a60a-0f5d93306cc9.png">
