### ISSUE TITLE
Message的接口建议增加超时参数

### ISSUE THREAD

**Issue by fidodido2503** [ChunelFeng/CGraph#80]
如题，在GMessage的send和rev接口建议增加超时参数，这样用起来更灵活一些，因为有些业务场景是不允许或者只允许很小的阻塞延时的

**Comment by ChunelFeng** [comment]
收到，非常感谢您的意见。今天也想了一下这个事情。

message的实现机制，是底层是一个 环形队列。通过 GMessage的类进行了一层包装。
暂时没有想到较好的 超时实现机制，如果您有思路，请提示 或者pr。再次表示感谢。

我暂时能想到的方式，是提供出来一个 类似 try_recv 的接口。如果没有消息，就返回 false，供上游调用。
这样实现起来，也相对简单一点。也能一部分迎合您提到的需求。

by the way，想简单了解一下你们的使用场景。非常欢迎 github或者微信交流。

**Comment by fidodido2503** [comment]
我的使用场景是视频分析和数据流的分析，本质上用的是流水线的构架，因为最近在重构所以关注到了你的这个项目，最近也在看代码，话说回来，今天又发现一个问题，底层应该也是因为同步队列的阻塞导致的，GMessage的发布订阅机制那里，如果发布者发送消息不及时或者没有发布，订阅者那里会一直阻塞，这导致一个比较严重的问题，他也会阻塞其他并行的节点运行，应该是engine那里一直在阻塞，我看应该是可以设置超时时间的，但是也肯定影响了其他无关节点的下次轮询的，你看看engine的run方法是不是需要更改一下，还有一个问题长时间的阻塞会占用线程资源，这个也是个问题

**Comment by ChunelFeng** [comment]
色图本身主要还是针对任务调度型的逻辑设计的，对视频流类似的场景，支持其实是不好的的。
message机制 是因为有人提到了 视频流的问题，我们才加入的。

你的意见是非常专业的。其实，如果真要做的话，可以用相对比较成熟的消息队列来做的，
正好能兼容本地和跨进程的逻辑。

message的发布订阅机制，其实想的是将当前的较长且逻辑无关的pipeline，拆分成两段，从而减少每段的执行时间。
但订阅一直卡住，不是 engine卡主，是等到消息的时候，有一个条件变量（在UAtomicRingBuffer中）等待可以通过。

**Comment by ChunelFeng** [comment]
你好，已在最新版本 [9d9f20f](https://github.com/ChunelFeng/CGraph/commit/9d9f20f2ee0b5a641f659bca7abb9cf1e8dd6e7d) 中，添加 CGRAPH_RECV_MPARAM_WITH_TIMEOUT 宏方法，
用于应对较长时间无 message发出的情况下， 停止等待的逻辑。



感谢大佬一键，欢迎随时指教
