### ISSUE TITLE
项目无法在C++11下编译成功，error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"

### ISSUE THREAD

**Issue by ATX735** [ChunelFeng/CGraph#81]
**Description**
按照原项目中的CMakeLists.txt配置无法通过编译，需将其中`set(CMAKE_CXX_STANDARD 11)`指定的C++11标准改为C++17`set(CMAKE_CXX_STANDARD 17)`才能通过编译。
根据编译错误提示，初步判断是代码中使用了C++17关键字`nodiscard`导致的。

**Environment**
OS：Windows 11
IDE：CLion 2020.1
Compiler：Visual Studio 2017
CMake 3.16.5

**Error Messages**
====================[ Build | T00-HelloCGraph | Debug ]=========================
"D:\Dev\CLion 2020.1\bin\cmake\win\bin\cmake.exe" --build G:\My_Program\GitHub\CGraph-fork\cmake-build-debug --target T00-HelloCGraph
Scanning dependencies of target CGraph
[  4%] Building CXX object CMakeFiles/CGraph.dir/src/DomainCtrl/Ann/DAnnNode.cpp.obj
DAnnNode.cpp
g:\my_program\github\cgraph-fork\src\cbasic\CStatus.h(81): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\cbasic\CStatus.h(85): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\cbasic\CStatus.h(101): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\cbasic\CStatus.h(109): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\cbasic\CStatus.h(117): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\cbasic\CStatus.h(125): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\cbasic\CException.h(29): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\UThreadPoolConfig.h(43): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\UThreadPoolConfig.h(54): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\queue\UAtomicQueue.h(122): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\queue\UAtomicQueue.h(131): note: 参见对正在编译的 类 模板 实例化 "CGraph::UAtomicQueue<T>" 的引用
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\task\UTaskGroup.h(69): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\task\UTaskGroup.h(84): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\queue\UAtomicPriorityQueue.h(81): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\queue\UAtomicPriorityQueue.h(90): note: 参见对正在编译的 类 模板 实例化 "CGraph::UAtomicPriorityQueue<T>" 的引用
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\queue\UAtomicRingBufferQueue.h(49): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\queue\UAtomicRingBufferQueue.h(125): note: 参见对正在编译的 类 模板 实例化 "CGraph::UAtomicRingBufferQueue<T,capacity>" 的引用
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\thread\UThreadBase.h(175): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\utilsctrl\threadpool\thread\UThreadBase.h(189): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\graphctrl\graphparam\../GraphManager.h(80): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\graphctrl\graphparam\../GraphManager.h(97): note: 参见对正在编译的 类 模板 实例化 "CGraph::GraphManager<T,__formal>" 的引用
g:\my_program\github\cgraph-fork\src\graphctrl\graphaspect\GAspectManager.h(87): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\graphctrl\graphelement\GElement.h(130): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\graphctrl\graphelement\GElement.h(136): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\graphctrl\graphdaemon\GDaemon.h(32): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\graphctrl\graphdaemon\GDaemonManager.h(36): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\graphctrl\graphpipeline\GPipelineManager.h(37): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\graphctrl\graphmessage\GMessage.h(59): error C2429: 属性 "nodiscard" 需要编译器标志 "/std:c++17"
g:\my_program\github\cgraph-fork\src\graphctrl\graphmessage\GMessage.h(65): note: 参见对正在编译的 类 模板 实例化 "CGraph::GMessage<T,capacity,__formal>" 的引用
NMAKE : fatal error U1077: “"D:\Dev\VisualStudio\VS2017 Community\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86\cl.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Dev\VisualStudio\VS2017 Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Dev\VisualStudio\VS2017 Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Dev\VisualStudio\VS2017 Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x86\nmake.exe"”: 返回代码“0x2”
Stop.

**Comment by ChunelFeng** [comment]
你好，感谢您的反馈，抱歉带来不好体验。  

CGraph 之前在本地 windows环境（CLion和 vs2015、vs2019）上均可直接编译通过。
在您机器上，nodiscard 无法编译的原因，暂时未知。可能跟编译器版本，和安装选项有关吧。

nodiscard 是纯修饰作用，无实际含义。如果后期无法查明原因，请直接删除就好。

欢迎pr

**Comment by ATX735** [comment]
PR已合并
