### ISSUE TITLE
并发run

### ISSUE THREAD

**Issue by zhaoguojie2010** [ChunelFeng/CGraph#87]
请问pipeline里支持并发的run()么？比方一个http服务，每个请求过来都执行同一个pipeline的run()方法来跑图，每个http请求都带有不同参数，但是这些参数好像没办法传给run方法。如果每个请求都新建一个pipeline的话直接就卡死了，好像程序进入死循环了。这个有办法解么？

**Comment by ChunelFeng** [comment]
您好，感谢关注。

如果是搭建http服务的话，目前比较推荐的方法，是 体检创建n个同样的pipeline（每个pipeline之间的参数是相互隔离的），然后通过 GPipelineManager中提供的  fetch和release 方法做互斥管控。

这里有一个参考demo：https://github.com/CDev-io/CGraph-NIO/blob/main/main.cpp  ，可以看一下。

至于http请求参数中参数传递到pipeline中的方式，可以创建新node，专门用于接收和解析；

也可以在 收到请求 && 进入pipeline 之前，直接调用 pipeline->getGParam<T>("key") 的方法进行赋值。

by the way，想了解一下您具体的应用场景是什么，以便今后交流。

**Comment by ChunelFeng** [comment]
还有一个，你说的那个并发run，应该 GPipelineManager 的 run方法就可以支持了。具体可以稍微看一下源码

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/37905059/226687212-f240615f-82c2-4ec3-9df5-47f5657da56b.png">

**Comment by zhaoguojie2010** [comment]
您好，感谢及时解答。我的场景是这样的：服务在启动时需要根据不同业务初始化好业务的执行图，用户会并发请求随机的业务。如果按照您上面的方案，我理解需要每个业务都建立一个GpipelineManager，然后每个GpipelineManager里面再建多个拓扑一样的pipeline。用户请求来了之后根据业务找到响应的GpipelineManager，再fetch出一个pipeline，再执行init和run。

如果我的理解没错的话，每个pipeline会有自己的线程池，用户并发很高的话需要建很多pipeline及线程池，导致context switch开销过大。这个有什么办法么

**Comment by zhaoguojie2010** [comment]
嗯，我按这个思路实现了一个简版的，4种pipeline，每种建10个。程序启动，执行完GPipelineManager::init()以后，8个核直接被占满了，prof如下
    ```
9154  26.7%  26.7%     9154  26.7% __lll_unlock_wake
    8379  24.4%  51.1%     8379  24.4% __lll_lock_wait
    6636  19.3%  70.5%     6636  19.3% __GI___sched_yield
    3947  11.5%  82.0%     3947  11.5% __pthread_mutex_trylock
    2593   7.6%  89.5%    11031  32.2% __GI___pthread_mutex_lock
    1963   5.7%  95.3%    11142  32.5% __GI___pthread_mutex_unlock
    1485   4.3%  99.6%    34288 100.0% CGraph::UThreadPrimary::run
      59   0.2%  99.8%     8438  24.6% _L_lock_791
```
这个现象有点奇怪，一直在跑CGraph::UThreadPrimary::run，是我哪里用的不对吗
pipeline倒是可以正常执行，就是性能非常差

**Comment by ChunelFeng** [comment]
哈哈，佬，这么晚了还在调代码。

方便的话，可以加您微信么，详聊。 

我的微信是 ChunelFeng，或者 扫描readme最下面的二维码

**Comment by ChunelFeng** [comment]
看了一下使用场景，属于后台服务场景。

CGraph 在init之后，后台的线程实际上是一直在执行抢任务逻辑的。
这些调度逻辑，是会占用系统资源的。

而且如果开辟多个 pipeline的话，当前逻辑下，是会开辟多个线程池的。
这一点也会消耗资源。

暂时的结论是，CGraph当前并不适合高并发的后台服务场景。
接下来，我们也会着力在这个点上，做一点改进和优化。

**Comment by ChunelFeng** [comment]
老哥，最新版本中提供的功能，是的多个 pipeline可以共享一个线程池资源，一定程度上缓解了这个问题。

例子参考：https://github.com/ChunelFeng/CGraph/blob/main/tutorial/T07-MultiPipeline.cpp

感谢您的关注。如果有意见和想法，请随时提出和指教
