### ISSUE TITLE
【bug】测试线程池，并发耗时任务，整体执行时长过大

### ISSUE THREAD

**Issue by arraytodd** [ChunelFeng/CGraph#9]
![image](https://user-images.githubusercontent.com/12149026/148967836-1719484a-ded3-41c5-8cb2-3a189ccb6108.png)

**Comment by ChunelFeng** [comment]
是这样的，这个线程池默认执行的时候，是开启4个thread，可以考虑修改下面的参数（CGRAPH_DEFAULT_THREAD_SIZE），然后重新执行试试看。

在8核心的机器上，您提到的这种情况应该能够得到一定程度的缓解。

![image](https://user-images.githubusercontent.com/37905059/148971304-44cc19b3-ebc0-4fea-846d-f9277add4afc.png)

如果其他有任何疑问，欢迎随时添加我的个人微信 （ ChunelFeng ），以便今后随便指教和交流

**Comment by arraytodd** [comment]
> 是这样的，这个线程池如果直接执行的时候，是默认开启 4 个 thread，可以考虑修改下面的参数（CGRAPH_DEFAULT_THREAD_SIZE）为 8，然后重新执行试试看。
> 
> 在 8 核心的机器上，您提到的这种情况应该能够得到一定程度的缓解。
> 
> ![image](https://user-images.githubusercontent.com/37905059/148971304-44cc19b3-ebc0-4fea-846d-f9277add4afc.png)
> 
> 如果其他有任何疑问，欢迎随时添加我的个人微信 （ ChunelFeng ），以便今后随便指教和交流

好的谢谢，刚没找到线程池数目--

**Comment by ChunelFeng** [comment]
> > 是这样的，这个线程池如果直接执行的时候，是默认开启 4 个 thread，可以考虑修改下面的参数（CGRAPH_DEFAULT_THREAD_SIZE）为 8，然后重新执行试试看。
> > 在 8 核心的机器上，您提到的这种情况应该能够得到一定程度的缓解。
> > ![image](https://user-images.githubusercontent.com/37905059/148971304-44cc19b3-ebc0-4fea-846d-f9277add4afc.png)
> > 如果其他有任何疑问，欢迎随时添加我的个人微信 （ ChunelFeng ），以便今后随便指教和交流
> 
> 好的谢谢，刚没找到线程池数目--

老铁，线程池类直接new的时候，可以通过传入参数的方式，
来设定线程池中的一些具体信息，比如初始线程数、最大线程数、任务调度方式等。

![image](https://user-images.githubusercontent.com/37905059/149664381-22a748c0-a393-4685-a4ca-b800772ef4ee.png)

再确认一下，您那边执行正常了么？？
